rust-lang/rls

- src/ls_server.rs
Otherwise it crashes immediately on Windows because it can't find `C:\tmp`
> Fixed hard-coded Linux-only log file path to use std::env::temp_dir()

- README.md
Figured this was just a typo
Typo in my typo fix, meant to title it 'Removed extraneous `is`
> README typo/ removed extraneous `if`

- .travis.yml
- Cargo.lock
- src/actions_http.rs
- src/actions_ls.rs
- src/build.rs
- src/ide.rs
- src/lsp_data.rs
- src/server.rs
- src/test/mod.rs
- src/test/types.rs
This also requires url v1.2.2 or higher for Url::to_file_path to work with URL-encoded drive letters on Windows.
---
Will need another update before it can be merged to update the rls-analysis and rls-vfs commit hashes in Cargo.lock after those PRs are merged.
> Use PathBuf and Path where necessary, and Url::from/to_file_path to convert between paths and file:// URLs.

- src/ls_server.rs
Also check for empty headers, which didn't have their own clause before.
These changes are mostly quality of life when trying to debug a new
client implementation, and `tail -f`-ing the log file.
This also pulls in a dependancy on the time crate, which is only
used for the pretty timestamps, which are not very important.
> Add log statments to start and end of server

- src/build.rs
> Account for arguments with spaces when building rustc commandline.

- src/server.rs
- src/test/mod.rs
Let's produce an error response for a malformed input, instead of silently terminating.
> Reply with error for malformed input

- src/ide.rs
This enables to remove `serde` from the dependencies of the rls-vfs, which I believe is the right thing to do (https://github.com/nrc/rls-vfs/pull/6). Not sure what this struct was intended for though, so I may be doing something stupid :)
> Remove dead code

- Cargo.lock
- Cargo.toml
- src/actions.rs
- src/lsp_data.rs
Notable improvements include a _much_ simpler API and the ability to
have racer::FileCache use the Vfs.
vfs::Error doesn't implement std::error::Error so there's an extra error
type introduced to satisfy the `racer::FileLoader` trait.
This shouldn't be merged until racer 2.0.0 is on racer's master branch.
See https://github.com/phildawes/racer/pull/632 for more info
> Update to racer 2.0.0

- Cargo.lock
Racer was writing to stdout which messed with JSON RPC of the RLS.
The CI for Racer includes a clippy lint now for detecting such usages of
stdout and failing if they are found.
> Fix racer println issue

- README.md
The first was closed in favor of the second.
> Readme: replace link to issue 9 by link to issue 88

- src/actions.rs
A URL will be auto-linked in a markdown text. Therefore, marking the URL
as markdown instead of being the language `url` makes the link
clickable.
Solves jonathandturner/rls_vscode#17
> Make document links clickable

- src/actions.rs
- src/lsp_data.rs
Reformatting this snippet triggers a `TypeError: Cannot read property 'substring' of null` for me.
```rust
fn main() {println!("Hello World")}
fn unused() {unreachable!()}
```
I fixed this by fixing `range_from_vfs_file` and using it to calculate the span to replace.
> FIX range calculation for reformatting

- Cargo.lock
- src/actions.rs
This is the counterpart of https://github.com/nrc/rls-vfs/pull/10.
The `.lock` file should be updated as well, but I think I can't do this before the other PR is merged.
> Use new `rls_vfs::Change` API.

- src/actions.rs
Fixed #161.
This is workaround.
I would like to open a PR to the rustfmt's repository, but unfortunately I don't know how to fix the bug in rustfmt.
The bug in rustfmt is that `format_input` returns `Ok` instead of `Err`:
https://github.com/rust-lang-nursery/rustfmt/blob/master/src/lib.rs#L494
> Fixed erasing of a document on reformatting if the document has parsing errors.

- Cargo.lock
- Cargo.toml
- src/actions/compiler_message_parsing.rs
- src/actions/lsp_extensions.rs
- src/actions/mod.rs
- src/main.rs
- src/test/mod.rs
- test_data/borrow_error/Cargo.lock
- test_data/borrow_error/Cargo.toml
- test_data/borrow_error/src/main.rs
This PR specialises Diagnostic for the RLS, enabling us to pass along an optional label on the primary range.  It also adds a new field for the secondary labels.
Adds intentionally failing test case to check for new behaviour.  This has also been tested and works with our existing vscode plugin, unchanged.
> Add primary label/secondary labels

- src/server.rs
The protocol specifies that the server must respond to the shutdown request in order to receive the exit request.
I need it to implement restarting in my extension.
Let me know if you have better solution.
Fixes #176
> Added responding to a shutdown request.

- src/lsp_data.rs
- src/server.rs
- src/test/mod.rs
This changed the jsonrpc version which is unrelated to the language server protocol version. There is no language server protocol version field.
Also check https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#example and http://www.jsonrpc.org/specification#response_object for the correct value of jsonrpc.
> Revert "First step moving over to lsp 3.0"

- src/server.rs
- src/test/mod.rs
I had a more elaborate fix but implementing tests for it was non-trivial due to how the message parsing directly calls out to stdin; there's no way for me to pass some other reader during testing.
I want to note that the current `read_message` implementation is not to spec: in particular it is only expecting a single header. The specification does not limit the possible number of headers, and at least the `content-type` header could be reasonably expected from some clients. 
In the course of playing around with the tests I ran into issues because I hadn't seen the guideline to pass `RUST_TEST_THREADS=1`; I added a check in the tests that will fail if that is not set. If there's some reason this is a bad idea, let me know. :) 
This closes #233.
> fix for #233

- src/actions/mod.rs
- src/lsp_data.rs
- src/test/mod.rs
This implements https://github.com/rust-lang-nursery/rls/issues/74 (Provide CompletionItem.kind from Language Server Protocol).
Right now we have a generic wrench icon applied to every completion:
After mapping from MatchType in Match from Racer completion results to an appropriate CompleteItemKind we get:
Not sure if the mapping is implemented in the right place - I only got inspired by already existing mapping function `source_kind_from_def_kind` in `lsp_data.rs`. This is obviously just an idea how we could do that.
We could even introduce mapping for `CompletionItemKind::Constructor` later on, for example for functions that return an owned version of Self, when we'll be able to retrieve a proper function signature. Until then we could possibly provide heuristics for functions called …
> Provide CompletionItem.kind for Racer completions

- src/build.rs
I tried to better convey that build request will be (re)initialized when current build dir is none or different that the one for which build has been requested.
Tried to introduce single match on `prev_build_dir`, but due to assignment inside I couldn't due to few issues, mostly with borrowing. If someone knows how to do it better, then please guide me :+1: Originally it was simply `if prev_build_dir.is_none() || prev_build_dir.as_ref().unwrap() != build_dir` instead of changing `reset`, but since eventually we check `reset` value twice here (initialize conditionally + check) anyway, I'm not sure that's better than checking, in one line, `is_none()`+`unwrap()` twice.
> simplified build request init logic

- src/actions/mod.rs
It happens when starting rls when cwd is different from project root.
> Fix incorrect diagnostic uris when cwd is different from project_path.

- contributing.md
Hi there,
I tried installing the RLS and found that I needed the zlib development headers, so I added that package to the installation commands.
I also figured that the setting of the environment variables can be simplified on MacOS and Linux.
> Small updates to build instructions

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- Fix https://github.com/rust-lang-nursery/rls/issues/270
- We don't have a code which converts configuration file to `Config` directly. We always load configuration file into `ParsedConfig` and create `Config` from it.
- So I think we can remove this simply.
> Drop rustc-serialize dependency

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/lsp_data.rs
- src/main.rs
- src/test/mod.rs
`hyper::Url` equals to `url::Url`. So we can remove `hyper` dependency.
> Remove needless hyper dependency

- src/config.rs
I believe this was a copy-paste mistake. Currently .toml config parsing, along with decoding enums is just copied from https://github.com/rust-lang-nursery/rustfmt/blob/master/src/utils.rs#L194 and https://github.com/rust-lang-nursery/rustfmt/blob/master/src/config.rs#L16. Bringing the original change allows us to define config enums again, like that:
```
configuration_option_enum! { CompilationType:
Binary,
Library,
}
```
to be used like that in rls.toml:
```
compilation_type = "Binary"
```
I checked enum value parsing with this change and it seems to be working.
> compilation fix: use impl_enum_decodable! from rustfmt

- .travis.yml
By upgrading to Trusty, we have sufficiently up-to-date packages to build
things. macOS has CMake 3.6 which is enough for us.
Also, there's no point of building dependencies twice with different
optimization level.
> Travis: improve speed

- Cargo.lock
- Cargo.toml
- src/build.rs
Stop ****ing semver:
- rls related crates are locked to 0.1 release.
- racer and languageserver-types are locked to the latest published release.
Building Cargo with nightly compiler is not necessarily a bad idea, so the code was updated to be 0.20.0 compatible.
> Bump dependencies

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
This is another attempt to fix the issue #280. 
Since the pull request #281 ran into problems due to the fact that `rls-span` and `rls-data` crates are actually used as API for interaction with Rust compiler, and have an embedded version of themselves inside it, changing them doesn't seem a good idea anymore.
Hence this alternative less invasive approach, which touches only `rls` and `rls-vfs` crates. Since it keeps using `rls-span 0.1` and `rls-data 0.1`, it works and passes all tests locally, including fresh compilers, and so I expect Travis to confirm.
I've reverted all changes in `rls-analysis` and `rls-vfs` that were made in preparation of #281, as they're conflicting with this attempt, and further edited `rls-vfs` to support this new way, which basically consists of adding `len` …
> Alternative attempt to support rangeLength field in LSP

- README.md
- src/config.rs
.rls.toml will be preferred over rls.toml, mirroring rustfmt's behaviour
resolves #295
> Allow config file to be named .rls.toml

- contributing.md
Now, this paragraph is needless for this repository.
This envvar is used by [rls_vscode][rls_vscode], but it have the same guide in [its repository][rls_vscode_guide].
[rls_vscode]: https://github.com/jonathandturner/rls_vscod://github.com/editor-rs/vscode-rust
[rls_vscode_guide]: https://github.com/jonathandturner/rls_vscode/blob/a5eb35e5745375ac1068593c938907b827c16a95/README.md#via-source
> Remove needless guide to set 'RLS_ROOT' from contributing.md

- Cargo.lock
- Cargo.toml
- src/cmd.rs
- src/test/mod.rs
- src/test/types.rs
This change includes to upgrade [languageserver-types](https://github.com/gluon-lang/languageserver-types).
It also contains to bump up the Language Server Potocol which our used to v3.
- Fix https://github.com/rust-lang-nursery/rls/issues/271
- Future work: https://github.com/rust-lang-nursery/rls/issues/299
> Upgrade Serde to 1.0

- src/main.rs
- src/test/mod.rs
- src/test/types.rs
- This fix https://github.com/rust-lang-nursery/rls/issues/303
- This is not a part of https://github.com/rust-lang-nursery/rls/issues/305
- This does not touch a part of constructing expected results because they compares partial strings with an actual results.
>  Use json! macro to construct json string for testing

- Cargo.toml
- build.rs
- src/main.rs
- src/version.rs
- The output format is `rls <version> (<commit hash> <build date>)`.
- This embed approach is based on [rustup.rs][rustup]'s code.
- rustup.rs is licensed under same licenses (Apache 2.0/MIT),
so I think there is no license problem.
[rustup]: https://github.com/rust-lang-nursery/rustup.rs/tree/a1c6be19add9c99f8d8868ec384aa76057fe7f70
- https://github.com/rust-lang-nursery/rls/issues/304
> Dump pkg version & build date & commit hash if run with `--version` flag

- Cargo.lock
- Cargo.toml
- src/cmd.rs
- src/test/mod.rs
Fixes #312.
- Update "languageserver-types" to 0.9.0;
- Modify initialization params to use `None` in experimental field of ClientCapabilities;
- Change tests to consider an empty object in "capabilities" instead of { "experimental": null }.
> Update language server types, making ClientCapabilities.experimental optional

- src/cmd.rs
Implement hover subcommand for #292
> Implement hover subcommand for #292

- src/cmd.rs
- src/main.rs
- src/server.rs
- src/test/mod.rs
Implemented https://github.com/rust-lang-nursery/rls/issues/305#issuecomment-302269982.
* Changed Notification/Method enum variant names to match those implicitly-defined in languageserver-types crate (used for fetching LSP method name from ServerMessage)
* Implemented simple serialize method for ServerMessages
* Removed string-based Message in tests, those now use ServerMessage in both mock_(raw_)server scenarios
> Use ServerMessages in tests

- Cargo.lock
See https://github.com/rust-lang/rust/issues/38584 for details.
> Update lockfile for gcc and cmake to fix build on MSVC 2017

- Cargo.lock
This is just a slightly more correct version of the gcc crate but shouldn't have any practical impact. Once https://github.com/rust-lang/rust/issues/42225 lands rls should build on Windows with VS 2017.
> Update gcc crate for MSVC 2017

- Cargo.lock
- src/actions/mod.rs
- src/config.rs
Although formatting is behind an unstable flag, I find it usable other than the lack of support for project rustfmt.toml, one of the bullets in #3 . If this isn’t the approach you’d like to take to configuring rustfmt (i.e. you want to pass it via `DocumentFormattingParams` or some other configuration scheme) feel free to reject.
Also, the recently added reformatting unit test fails for me even before this change with a rustfmt parsing error.
> Support formatting config via rustfmt.toml

- src/build.rs
- src/main.rs
Fixes https://github.com/rust-lang-nursery/rls/issues/290. Although this seems to fix the issue with missing env vars causing compilation failures in some projects, there may be a better way of doing that in the long-term by not having to call rustc to get dep-info, judging from the comment in code.
> Set missing env vars from Cargo in a compilation step

- Cargo.lock
- src/build.rs
Pull in the most recent changes from Cargo to get the rls compiling again.
> Update dependency on Cargo

- src/test/harness.rs
- src/test/mod.rs
- This intend that `test/mod.rs` only have test functions.
- This is just clean up.
> Split test harness code into test/harness.rs

- src/build.rs
Fixes https://github.com/rust-lang-nursery/rls/issues/330. Thanks to @nrc's suggestion, using `BTreeMap` instead of `HashMap` retains RUSTFLAGS order with which crate fingerprint has been made when compiling dep crates, thus not triggering complete project rebuild per each cargo run.
> Prevent aggressive project rebuilding by retaining RUSTFLAGS order

- Cargo.lock
From racer's changelog, this update:
* Support completion after using try operator ?
* Find methods on cooked string literals
* Fix bug caused by closure completions feature
* Find static methods on enums
* Find doc comments on named and indexed struct fields
* Find pub(restricted) items
> Update racer from 2.0.8 to 2.0.9

- Cargo.lock
- src/actions/mod.rs
- src/server.rs
- src/test/mod.rs
- test_data/reformat_with_range/Cargo.lock
- test_data/reformat_with_range/Cargo.toml
- test_data/reformat_with_range/rls.toml
- test_data/reformat_with_range/src/main.rs
Implements #333 
This PR request Rustfmt to format a range of text.
However, with the return value from Rustfmt as a factor, in response to LanguageClient, the text of the whole file is sent.
> Format ranges

- src/actions/lsp_extensions.rs
- src/server.rs
Add missing REQUEST__Deglob needed by https://github.com/rust-lang-nursery/rls/commit/bdcc0aea6062610be3c8b9c5db77731f79856cbb.
As a side note, should all method strings in [here](https://github.com/Xanewok/rls/blob/d8805a1fc5a33ac889ab35ebd56153882bc7de41/src/server.rs#L234) be replaced by appropriate `REQUEST__*` and `NOTIFICATION__*` identifiers from languageserver-types?
> Fix compilation

- README.md
- rls/src/build.rs
- rls/src/config.rs
- rls/src/test/mod.rs
- test_data/multiple_bins/Cargo.lock
- test_data/multiple_bins/Cargo.toml
- test_data/multiple_bins/rls.toml
- test_data/multiple_bins/src/main.rs
- test_data/multiple_bins/src/main2.rs
Added `build_bin` configuration, which allows to specify which crate should be compiled and analyzed. When both `build_lib` and `build_bin` are specified, `build_lib` is preferred.
> Support analyzing a specific binary in project

- appveyor.yml
- src/test/mod.rs
Cleaned and updated AppVeyor CI configuration:
* Removed old, unnecessary `RUST_TEST_THREADS=1`
* Use default Rust toolchain for corresponding i686/x86_64 target (i.e. don't cross-compile from x86_64 to i686)
* Check compilation of both build/test configuration
> Update AppVeyor settings

- src/build.rs
- src/config.rs
> Added wait_to_build time to config

- src/server.rs
> handle both number and string ids

- .gitignore
It's only a convenience, but since https://github.com/rust-lang-nursery/rls-vscode is the recommended/reference client and now provides tasks.json, it might be a good idea to ignore the vscode workspace settings altogether for now.
> Ignore .vscode and .idea directories

- src/actions/mod.rs
- src/build.rs
- src/config.rs
Issue #252 
- Added `show_warnings` to config
- Implemented in `convert_build_results_to_notifications`
- Made config in `BuildQueue` public
First, am I filtering in the right place? This works, but I'm not sure if there is a better place to put the filter. Also, adding `pub` to `BuildQueue` feels dirty. Should config be some sort of shared object or accessed via method call?
> Add show_warnings to config

- src/actions/mod.rs
It is okay to have an empty result
> Fix #405 by making no results not cause a failure.

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/cmd.rs
- src/main.rs
- src/server.rs
- src/test/mod.rs
Laying foundations for https://github.com/rust-lang-nursery/rls/issues/395, https://github.com/rust-lang-nursery/rls/issues/376 and proper https://github.com/rust-lang-nursery/rls/issues/360 - JSON-RPC conformance in general and tidying the server flow logic a bit.
* Pulls in `jsonrpc_core::Id` for the `number | string | null` id type in JSON-RPC which we didn't support until recently
* Introduces more error codes
* Uses `jsonrpc_core` structs instead of our custom ones for failure/error message logic.
I have also some pending WIP changes planned for `{Notification,Request}Message` ([here](https://github.com/rust-lang-nursery/rls/blob/master/src/lsp_data.rs#L176-L217)), but I still need to work on stronger typifying, will probably land with …
> Use jsonrpc-core data for improved and more consistent error handling flow

- src/build/cargo.rs
- src/build/mod.rs
- src/build/rustc.rs
- src/config.rs
- src/test/mod.rs
- test_data/simple_workspace/Cargo.lock
- test_data/simple_workspace/Cargo.toml
- test_data/simple_workspace/member_bin/Cargo.toml
- test_data/simple_workspace/member_bin/src/main.rs
- test_data/simple_workspace/member_lib/Cargo.toml
- test_data/simple_workspace/member_lib/src/lib.rs
This is a prototype implementation for workspace support (https://github.com/rust-lang-nursery/rls/issues/132). It introduces these new options:
* `workspace_mode` - new behaviour is opt-in via this flag
* `analyze_package` - specified which package will be analyzed in workspace mode
The only thing that's not behind a `workspace_mode` check of some sorts is detection of package root manifest path [here](https://github.com/rust-lang-nursery/rls/compare/master...Xanewok:workspaces?expand=1#diff-9300feef84bdf7e5ab58b05fa4eb0794R547) It uses only .json file save-analysis data and uses Cargo exclusively, so there's a lot of room for possible optimizations. 
Tested on [webrender](https://github.com/servo/webrender) workspace and [simple_workspace](https://github.com/Xanewok/rls/commit/3f8e3f271a …
> Workspaces

- src/actions/mod.rs
- src/config.rs
By setting build_on_save to true, the project is only build if a file of the
project got saved. The default value is false and will build the project if a
file in the project changed.
Fixes #385
> Adds build_on_save config option

- src/actions/mod.rs
- src/build/mod.rs
- src/lsp_data.rs
- src/server.rs
- src/test/mod.rs
- test_data/omit_init_build/Cargo.lock
- test_data/omit_init_build/Cargo.toml
- test_data/omit_init_build/src/main.rs
Fixes https://github.com/rust-lang-nursery/rls/issues/419.
* Introduces new `InitializationOptions` structure defining options that are supported via `initialization_options` in `initialize` request.
* Allow for not building immediately after `initialize`, configurable via `omit_init_build` in `InitializationOptions`
* Bump up build priority from Normal to Cargo when compilation context isn't cached yet (in case we omit first build, don't catch `onDidChangeConfiguration` and start a Normal build - we always need Cargo as a first to resolve and build deps etc.)
> Opt-out of build after `initialize`

- Cargo.lock
Increases the cases where racer will find matches, and addresses issues around closures and trait impls that could previously confuse racer.
> Update racer to 2.0.10

- src/actions/mod.rs
- src/lsp_data.rs
(Somewhat) fixes #421 (and related).
This is a QoL (short-term) fix implemented as per @nrc's https://github.com/rust-lang-nursery/rls/issues/421#issuecomment-316521033:
> I think the best short-term solution is to not crash, notice non-file URLs and just ignore them.
This basically introduces `UrlFileParseError` implementing `Error` and it's now returned in a `Result<T, UrlFileParseError>` for `parse_file_path` and `convert_pos_to_span`, which uses it.
On an error that's related to invalid URI scheme, it just returns from the handler function.
`$log_name` and `$uri` variables in macro are used only for the underlying `trace!` macro call and I can remove them if it makes things unnecessarily verbose (repeating function name as literal, separating uri binding for clarity etc.).
I know …
> Ignore invalid file URI scheme in parse_file_path et al.

- src/actions/mod.rs
- src/config.rs
This probably fixes #431 and related.
In the current implementation serialization for RLS options can fail if not every option is provided, and if that happens, configuration is essentially ignored. Since for some time few options weren't included in the VS Code (and possibly ignored completely when using different clients) extension, user configuration had no effect.
This makes it so that missing options are set to the values set in `Default` impl for `Config`.
> Don't ignore incomplete server config, use default values if needed

- src/actions/mod.rs
- src/build/cargo.rs
- src/build/environment.rs
- src/build/mod.rs
- src/build/rustc.rs
- src/test/mod.rs
- test_data/simple_workspace/member_lib/src/lib.rs
This is a first step to not be as reliant on Cargo and makes it so RLS uses linked compiler instead of `rustc` or `$RUSTC` process.
Passing analysis data from the compiler should be faster in few cases since analysis data will be passed in-memory, rather than unconditionally via file on disk. Additionally `cargo` routine can now collect diagnostics messages and display them until subsequent bare `rustc` build routine is performed.
> Use linked compiler during Cargo `exec()` callback

- src/build/cargo.rs
- src/build/mod.rs
- src/build/plan.rs
Incomplete `build::plan::Plan` is created, containing an inter-package dependency graph and targets/features of packages in the workspace scope, and stored when performing the Cargo build routine.
It's not currently used and specific data held will require further design and work.
For now copies some of the Cargo types, as some members are not yet publicly exposed.
> Create simple dep-graph from Cargo metadata

- src/actions/mod.rs
- src/build/cargo.rs
- src/build/mod.rs
- src/config.rs
- src/test/mod.rs
- test_data/infer_bin/Cargo.lock
- test_data/infer_bin/Cargo.toml
- test_data/infer_bin/src/main.rs
- test_data/infer_custom_bin/Cargo.lock
- test_data/infer_custom_bin/Cargo.toml
- test_data/infer_custom_bin/src/custom_bin.rs
- test_data/infer_lib/Cargo.lock
- test_data/infer_lib/Cargo.toml
- test_data/infer_lib/src/lib.rs
This is only a proof-of-concept and needs some ironing out. Most importantly it'd be good to handle properly inferred/default and explicitly stated values when updating the config via LSP message. Additionally, it'd be good not to duplicate code that creates a `Workspace`, although I'm not really sure how to do that, as Workspace needs to be created with borrows and I'm not sure how to cleanly separate a struct that would hold the data and Workspace without running into self-borrowing issues when initializing.
Right now it works like this: On RLS initialize, call `infer_config_defaults` which creates a `Workspace` and queries appropriate package's targets to see which crate targets are available (including inferred `lib` and `bin` ones). Then, these are set as follows: prioritize `lib` …
> Infer appropriate crate target from workspace

- contributing.md
- src/actions/mod.rs
- src/server.rs
- src/test/mod.rs
- test_data/find_impls/Cargo.lock
- test_data/find_impls/Cargo.toml
- test_data/find_impls/src/main.rs
I tried using the recent addition to the save-analysis data to tackle two items from the wishlist.
1. Find all implementations of trait.
Listed under wishlist rust-lang-nursery/rls#142
Fails for traits which are implemented using derive
2. Find supertrait of trait
Listed under wishlist rust-lang-nursery/rls#142
Only proof of concept, not yet transitive.
To Check: Which span makes more sense. The span of the supertrait (as
currently) or the span of where the subtrait defines the dependency?
Requires the find-impls branch of https://github.com/jonasbb/rls_vscode
Also requires the find-impls branch of rls-analysis.
I have a few specific questions which I am not sure how to tackle them:
1. Find all implementations on a library provided trait like `PartialEq` only produces spans with a file …
> Implement find implementations extension

- Cargo.lock
- src/build/cargo.rs
- src/build/mod.rs
- src/build/plan.rs
Depends on #448. Since it seems this PR also pulls this automatically, I'm not sure if it's possible to merge one and the other with proper history, so I can update this PR if #448 will be merged to include only the last commit.
Also depends on https://github.com/rust-lang/cargo/pull/4416, so until that's merged, I'm using the https://github.com/Xanewok/cargo/tree/more-executor-params branch with the changes.
By exposing `&Unit` in `Executor::init()` we can create a target dependency graph with ease, without having to explicitly copy over any Cargo code. This only currently fetches the dep graph after each `cargo` build routine, an example output (done for the `rls` itself) can be found here: https://pastebin.com/iSz4pcuK.
Next stage should be to cache exact `ProcessBuilder`s for executed …
> Create and cache inter-target dep graph during Cargo build routine

- src/build/cargo.rs
- src/build/plan.rs
Followup to #449. This limits the inter-target dep graph to the targets in the workspace and caches appropriate `rustc` commands (after being modified by the RLS) for appropriate units to build.
This still needs implementing fetching dirty target dep graphs, sorting the nodes topologically and implementing a simple job queue. If this is too little to merge right now, I can push more changes to this branch so more work can be merged at once if needed.
> Cache processes to execute for the workspace inter-target dep graph

- contributing.md
It appears that the `easy` label was replaced in favour of the `good first issues` label.
> [Documentation] Update the starter issues URL

- src/actions/mod.rs
This reverts commit ca84ba5c2a8498425d6002739325d3ebbf267f2e.
Other `parse_file_path!`s have also `&` arguments and this fixes a compilation error.
@nrc r?
> Revert "Remove unnecessary `&`"

- src/actions/mod.rs
- src/actions/post_build.rs
- src/lsp_data.rs
- src/server/io.rs
Fixes #43.
Subject line is maybe a bit confusing since this specializes `Output.notify` over the argument, but generalizes it over the encoding.
I was tempted to replace `lsp_data:: NotificationMessage` with [`jsonrpc_core::types::request::Notification`](https://docs.rs/jsonrpc-core/7.1.1/jsonrpc_core/types/request/struct.Notification.html) but that structure doesn't permit us to keep using [`languageserver_types::PublishDiagnosticsParams`](https://docs.rs/languageserver-types/0.12.0/languageserver_types/struct.PublishDiagnosticsParams.html).
> server: generalize Output.notify

- src/actions/notifications.rs
- src/server/mod.rs
This fixes the problems mentioned here: https://github.com/rust-lang-nursery/rls/issues/214#issuecomment-330675842
Changed the `param` of `RawMessage` to represent the lack of parameters internally with a `serde_json::Value::Null`. This is because it's hard to parse `Option<serde_json::Value>` into an arbitrary type (an associated type of a `Notification` or a `Request`), as it doesn't implement `Deserializable`. Once `TryFrom` stabilises, I think it can be used, if `Option<serde_json::Value>` is preferable.
With these fixes, RLS now works for me with SublimeText and LSP.
Also, I found out as a new contributor that it was hard to know which version of RLS was running inside your editor, so I added version printing in the debug logs, like this: `Language Server Starting up. Version: …
> Fixed parsing NoParams. Added version printing to debug logs. More types now derive Debug.

- src/actions/notifications.rs
- src/build/cargo.rs
- src/build/mod.rs
- src/build/plan.rs
WIP: This needs only plugging the logic in the `build/mod.rs`, which is relatively a small amount of work, but wanted to get a feedback if things are going in a good direction.
@nrc could you take a look and tell me if the overall design is good and if there are any obvious mistakes? I tried to debug and test intermediate functions and behaviour using the RLS and different crates and it works as intended, at least from what I tested on single-package projects.
This probably still will need some tweaking on the vfs side, as `vfs.get_changes().iter().map(|(k,_)| k.clone()).collect()` seems to retrieve not only dirty files, also disk-synced files, which are only open (which might fool the dirty crate heuristics).
> Use cached build plan mostly instead of Cargo to schedule a multi-target build 

- src/actions/post_build.rs
- src/build/rustc.rs
- src/test/mod.rs
- test_data/unicødë/Cargo.lock
- test_data/unicødë/Cargo.toml
- test_data/unicødë/src/lib.rs
Fixes rust-lang-nursery/rls-vscode#151.
Here is more context on the issue: https://github.com/rust-lang-nursery/rls-vscode/issues/151#issuecomment-331621292.
In short, `convert_message_to_json_strings()` didn't fully reconstruct utf-8 characters.
@nrc what's the cause for the [FIXME](https://github.com/rust-lang-nursery/rls/compare/master...Xanewok:utf8-diagnostics?expand=1#diff-48b18d7151f11423d709ca98bee07cefL187)?
The function is only called for rustc, not Cargo.
It looks like emitting json from rustc works, from what I can tell (am I missing something?) and that separate messages are emitted in each line, so I:
1. naively parse the string from utf8-stream (safe?)
2. split by lines
3. return the `Vec<String>` containing json strings
However, I'm not sure if that's correct/safe approach …
> Preserve UTF-8 file path in the resulting compiler diagnostics

- Cargo.lock
- Cargo.toml
- src/actions/requests.rs
- src/server/mod.rs
- src/test/mod.rs
- test_data/workspace_symbol/Cargo.lock
- test_data/workspace_symbol/Cargo.toml
- test_data/workspace_symbol/src/foo.rs
- test_data/workspace_symbol/src/main.rs
Support for workspace/symbol, https://github.com/rust-lang-nursery/rls/issues/353
Depends on https://github.com/nrc/rls-analysis/commit/f04c79c9d3c02b6529c3098edd9256202674832b , so Cargo.toml will need to be updated with the new rls-analysis version (once it's released) to compile.
> support "workspace/symbol" lookup

- src/test/mod.rs
- test_data/unicødë/Cargo.lock
- test_data/unicødë/Cargo.toml
- test_data/unicødë/src/lib.rs
Fixes #506.
This removes the unicode test data folder for now. Faulty handling
prevents building rustc under macOS, so the test itself is also
commented out for now. When this is fixed, this test should be restored
(revert this commit) or reintroduced when another test harness is
introduced.
> Revert the UTF-8 test directory in the repository

- Cargo.lock
- Cargo.toml
- src/lsp_data.rs
- src/test/mod.rs
This will allow implementation of new DefKinds. 
The test needed to be adjusted because three new DefKind values were introduced, two of which were inserted at positions before DefKind::Struct.
> Update rls-analysis and rls-data dependencies

- src/build/cargo.rs
- src/config.rs
- src/test/mod.rs
- test_data/features/Cargo.lock
- test_data/features/Cargo.toml
- test_data/features/src/main.rs
I just mirrored the cargo build option within the rls config struct.
For some reasons I have some tests writing to stderr, I can't figure out where this is coming from. I don't know if it's a problem in my tests or not.
> Add support for cargo features

- Cargo.lock
- Cargo.toml
- test_data/common/Cargo.lock
This updates the rustfmt dependency. 0.2.8 was breaking starting with rustc nightly 2017-10-15.
See https://github.com/rust-lang-nursery/rustfmt/issues/2061
> Update rustfmt dependency

- src/test/mod.rs
This was changed in f1c85ebcb196ff0c0374d74f2140e75382bf4e06 to account
for the new DefKinds in rls-data. However, this will not pass rustc
tests (i.e. `./x.py test src/tools/rls`) when updating the RLS submodule
in that project. I believe this is because the versions of rls-data are
different between rustc and the rls. In order for the RLS to be updated
with rustc, this test should be updated to pass. Then, once that change
is release to the nightly channel, the tests in this repo will pass
again.
I have tested this theory when running a locally built version of rustc
that has the lastest commit of the RLS (5930bab4ae6343bea0d8dec171e895b09cade5a4)
as the tip of the rls submodule. These tests pass in both the rustc and
rls repositories then.
Also, the previously referenced commit was …
> Revert test for workspace_symbol

- src/server/mod.rs
- src/test/mod.rs
This pull request fixes the RLS not sending response when result is empty such as when the result of type Ack.  I came across this when experimenting with using the RLS in Eclipse via LSP4E/LSP4J. Those libraries wait for a response even if the result is expected to be empty or null. I'm an new at rust so this may be an inappropriate way to solve the problem.
> ack_responses

- src/actions/requests.rs
Adjusts the response to the completionItem/resolve message to be a single CompletionItem. 
Reference:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completionItem_resolve
> Fixes completionItem/resolve response to match the LSP specification.

- src/test/mod.rs
The `bin_lib_project` and `bin_lib_project_no_cfg` tests can intermittently fail when run in parallel, especially when running them in the rustc x.py tests. This commit temporarily removes one of those tests. The test is still legitimate, but we need to find a way to be able to use the same test project directory (lib_bin) in tests, and make sure that they work when testing in the CI environment.
See #524.
> Remove intermittent failing test

- src/build/cargo.rs
This is consistent with treating the RHS of the first equals sign as an opaque value, which seems to be how the current code behaves for things with only one equals sign. It seems like there could be issues with that approach in general (i.e. some semantic understanding of the flags could be needed instead of just picking the last blob you saw), but this seems to solve the more immediate problem of multiple equal signs in arguments.
> Handle arguments with nested equal signs (fixes #512)

- contributing.md
The flag was changed in https://github.com/rust-lang/rust/pull/43327.
r? @nrc
> Mention RUSTC_SAVE_ANALYSIS in contributing.md

- src/test/mod.rs
Running `cargo test` fails due to `test_workspace_symbol`. This PR fixes it. 
Sorry if the failure ought to be intentional, I could not find any relevant issues myself.
> Fix a test which keeps failing

- src/server/mod.rs
`rootPath` is deprecated and some newer clients only send `rootUri`. Specifically, I want to compare the two Vim clients I've found, but one of them can't be used with current RLS.
Before this patch RLS will panic if there's no `rootPath`. After this PR we accept `file://` URIs and prefer them to `rootPath` if both are specified. Passing `rootPath` only should still work as well.
I'm not sure where to put the tests and how to organize everything. Another test in `server/mod.rs` is also included in the root. Should they be put under a `mod test`?
I could add more tests too. What coverage is the project looking for at this stage?
Related to #299.
I'll hang out in Gitter and here if you have feedback!
> Accept rootUri at initialization

- src/actions/mod.rs
- src/actions/notifications.rs
A big improvement for *atom-ide-rust*.
Resolves #531
> Ignore irrelevant `DidChangeWatchedFiles` notifications

- contributing.md
- debugging.md
- src/actions/requests.rs
- src/build/cargo.rs
- src/build/environment.rs
- src/build/mod.rs
- src/build/rustc.rs
- src/cmd.rs
- src/server/io.rs
- src/server/mod.rs
- src/test/harness.rs
- src/test/mod.rs
This is the result of me testing out a WIP source code spell-checker
and your project was the random target this time.
In  addition to these changes,
there is also a unfixed typo in external crate languageserver-types, `unregisterations` as used at https://github.com/rust-lang-nursery/rls/blob/master/src/actions/notifications.rs#L221 and defined in https://github.com/gluon-lang/languageserver-types/blob/ee0020870dbca2c96f777c1962f07d3ad74afd9b/src/lib.rs#L1169
> fix some typos, and use consistent US spelling of analyze

- appveyor.yml
inInvalidating cache on file change is described [here](https://www.appveyor.com/docs/build-cache/#configuring-cache-items).
I believe it makes sense to rebuild the cache when we change package set we pull for the build.
If the cache is updated incrementally (I believe it is? [recently](https://ci.appveyor.com/project/jonathandturner/rls-x6grn/build/1.0.655/job/p5ndgjpu6k9np32p#L344) ~400mb cache update was rejected because the limit of 1GB was exceeded) there's no point in leaving behind obsolete build artifacts - maybe this contributes to cache corruptions?
> Invalidate AppVeyor cache on Cargo.lock change

- debugging.md
This also removes the mention of `showStderr` vscode extension option, which was removed due to a bugfix.
> Clarify server/extension debugging

- .travis.yml
- appveyor.yml
Currently the release compiler is used in CI testing. If we used the debug compiler here we could cut down our full re-builds from ~30 minutes to ~10. And re-builds on the same nightly / cache to ~3 minutes.
The debug compiler seems pretty much designed for CI - fast builds to prove correctness. Obviously fast CI testing is valuable for handling PRs. I had a quick look through the last couple of blame commits but couldn't see a reason to use _--release_. I'd be interested to learn why it's worth the extra effort.
> Use the debug compiler for CI testing

- .travis.yml
- Cargo.lock
- Cargo.toml
- appveyor.yml
Trying a fix in https://github.com/rust-lang-nursery/rls/pull/542#issuecomment-342042489, let's see if CI will pass it for now.
Updates Racer to 2.0.12.
> Update Racer, add rust-src component to CI

- appveyor.yml
This probably makes more sense than invalidating `target` on Cargo.lock - when we change the lockfile, it's a good idea to start clean when fetching deps. We might not need previously downloaded packages after updates, preventing from bloating up the registry after numerous Cargo.lock updates.
Full dep download cycle takes additional ~1 minute, but will only happen on Cargo.lock update (which is rare).
r? @nrc
> Invalidate Cargo registry on Cargo.lock change in AppVeyor

- src/cmd.rs
The `symbol` command looks up a symbol using `workspace_symbol`. I've tested against the `test_data/workspace_symbol` project and it works as expected.
I opted to call it `symbol` instead of something more verbose. It's possible to get it confused with `symbols`, but I'm willing to take that risk.
I also don't know what should be put in the `used for 'xxx'` text, so I left it out. Feedback welcome.
> Add `symbol` command to CLI (workspace symbol)

- src/cmd.rs
It's not obvious that the line and column numbers are zero indexed. Maybe this little text will make it more obvious for the next person using it.
> Explain that line/column numbers are zero indexed

- src/main.rs
This is instead of an arbitrary argument. See
https://github.com/rust-lang-nursery/rls/issues/507
(This replaces #568 with a rebase instead of a merge)
> Use `--cli` to start the cli

- src/actions/requests.rs
- src/server/mod.rs
- src/test/harness.rs
- src/test/mod.rs
- test_data/deglob/Cargo.lock
- test_data/deglob/Cargo.toml
- test_data/deglob/src/main.rs
Provide code actions for deglobbing import for wildcard imports, except
for `prelude::*`. To avoid false positives (*) in the code actions, the
deglob command is run before the code action is presented to the user.
The original custom LSP extension is still in place in works. As such
the `Deglob::handle` function is split into a new
`calculate_workspace_edit`, which calculates the data for the deglob
action and is not used to the code action. The original `Deglob::handle`
just calls this function and is reponsible for sending the messages to
the client.
Addresses https://github.com/rust-lang-nursery/rls/issues/515
(*) The path in `CodeAction::handle` only checks for the existence of `use ` and `::*`. False positives could be multiline strings or doc comments.
> Implement Deglob as a CodeAction

- README.md
Racer can now gets the Rust stdlib source path from `rustc --print sysroot`, so the users don't need to have to bother setting it up once they have the `rust-src` component installed.
> No need for Racer installation instructions anymore

- src/actions/mod.rs
- src/actions/notifications.rs
- src/actions/requests.rs
- src/build/mod.rs
- src/cmd.rs
- src/server/dispatch.rs
- src/server/io.rs
- src/server/mod.rs
- src/test/mod.rs
As a result of the #540 discussion I've implemented an optional off-main request handling thread mainly to handle client request spam without locking up the server for arbitrary time. (This PR includes/builds on #552).
This change does add complexity to the life of a request. However, it actually simplifies the implementation of these requests, as the new `Dispatcher` provides running on the `WORK_POOL`, timing out & checking the request is outdated without these needing to be implemented per-request _(as timeouts used to be)_. As such the `fn handle(...)` of the requests I adapted to be non-blocking are now simpler.
Currently we essentially have a single thread that
* reads stdin
* parse request
* processes request
* sends response on stdout
This is simple and provides order correctness. …
> Add stdin-nonblocking request handling

- src/actions/requests.rs
It was ignoring the requested file and could send some positions of
differents files in the project.
This commit fix this behavior and now sends only positions in the
requested file.
I could observe this behavior:
> fix: filter documentHighlight positions to the requested file

- contributing.md
I forgot about the documentation of custom RLS commands during https://github.com/rust-lang-nursery/rls/pull/567
> Remove documentation of obsolete rustWorkspace/deglob command

- src/actions/requests.rs
- src/server/dispatch.rs
- src/server/mod.rs
- src/test/mod.rs
Move these requests to no longer block stdin (following #565), as we benefit from have all requests not block stdin.
* Formatting
* RangeFormatting
* ResolveCompletion
These requests will now be subject to the default timeout. 
As timeouts are feasible for any request (as they can be caused by the previous requests timing out), I'm not sure if I got the `fallback_response` impl right by returning an error. Perhaps in some cases we'd prefer to silently timeout?
```rust
Err(ResponseError::Message(
ErrorCode::InternalError,
"Reformat failed to complete successfully".into(),
))
```
> Add nonblocking Formatting, RangeFormatting, ResolveCompletion

- src/build/cargo.rs
Without this change, when RLS hits a cargo workspace, without being in workspace_mode, the following happens:
1.  ws.current() returns an error, unwrap() panics.
2.  The panic occurs while holding the rls_config lock, so the lock gets poisoned.
3.  The main thread panics the next time it attempts to lock the config.
4.  On my machine at least, this triggers Microsoft/vscode-languageserver-node#279 where the client experiences a sort of endless recursion, repeatedly trying to send a message to the server, and failing, which causes it to try again.  The vscode process eats up all of my memory, causing my machine to crawl until it finally pops up a bar saying that the extension host process was terminated.
With this change, RLS just doesn't really work when it hits a cargo workspace with …
> Don't panic if we hit a cargo workspace when not in workspace mode

- src/actions/post_build.rs
- src/build/cargo.rs
- src/build/mod.rs
- src/build/plan.rs
- src/build/rustc.rs
This removes the BuildResult::Failure variant. It was used
interchangeably with BuildResult::Success, and only returned in rustc()
routine when executed in-process compiler panicked or returned with a
non-zero exit code.
Since internally the compiler driver also panics on compile failure, the
BuildResult::{Failure, Success} variant distinction didn't give any
meaningful information, as the driver treats ICEs and regular compile
failures the same way. In both cases BuildResult::Failure was returned.
More correct solution would be not to panic on regular compile failure
in run_compiler, so the caller can either catch a panic and deduce that
an ICE was encountered, or receive a non-zero (101) exit code in case
errors were encountered.
Then a BuildResult::Err variant would be returned on an …
> Simplify BuildResult enum

- src/actions/requests.rs
Formatting errors like "line exceeded maximum width" shoudn't cancel formatting.
Fixes #591.
> Ignore formatting errors

- src/actions/mod.rs
- src/actions/notifications.rs
- src/actions/post_build.rs
- src/lsp_data.rs
- src/server/io.rs
- src/server/mod.rs
Work towards #602. Since I'll want use different notifications (`window/showMessage`) than the currently hardcoded PublishDiagnostics and `rustDocument/*` ones, I tried to generalize the `Output::notify`, which is now easily possibly thanks to `Action` trait (thanks @alexheretic!).
The trait is generic enough (provides method and params type) to be easily reused, but it's not as clean as it could be - per documentation implementers are messages handled by the server (so client->server), whereas I added implementation of the ones sent to the client instead.
Ideally this should be solved using https://github.com/gluon-lang/languageserver-types/issues/19 (which I didn't do yet... :cry: ).
Additionally replaced `NoParams` with `()`, as these serve the same purpose and not to introduce another …
> Simplify outgoing notifications, remove NoParams

- .travis.yml
- Cargo.toml
- src/actions/mod.rs
- src/actions/requests.rs
- src/config.rs
- src/main.rs
Proof of concept for https://github.com/rust-lang-nursery/rls/issues/149#issuecomment-348174639
> Make rustfmt an optional dependency

- Cargo.toml
merging with github with the `rebase` strategy (to not have a merge commit) should allow you to not have to manually push around commits on the command line.
> Update rustfmt dependency on the pathbuf branch

- Cargo.lock
- Cargo.toml
- src/actions/requests.rs
use matching_defs to provide case-insensitive completion for `workspace/symbol` lookups
resolves #514
Supported by existing `workspace/symbol` and rls-analysis tests. Happy to add a few more if we think it's necessary!
> Expand workspace/symbol matches

- Cargo.lock
- Cargo.toml
- src/build/cargo.rs
- src/config.rs
- src/main.rs
- src/test/mod.rs
This should allow us to have workspaces on by default inside the Rust repo.
r? @Xanewok 
The significant change here is that we no longer specify a package to Cargo and trust that it will do the right thing - when in the workspace root it will build everything and when in a sub-crate, just build that crate (and its deps). This was pretty easy because of changes to Cargo since the original work.
> Get tests working inside a workspace

- README.md
> changing readme to stable, fixes #611

- README.md
Some users might have rustup toolchain default to nightly.
Also, condense them into one line for easier copy-pasting.
> Specify stable toolchain explicitly when install from rustup.

- src/actions/mod.rs
- src/actions/requests.rs
- src/lsp_data.rs
- src/server/mod.rs
The current behaviour is to send snippets regardless of the client
capabilities communicated in initialize. This change makes sure the
RLS only sends snippets for completion items when the language client
has specified that it supports snippets.
Fixes #629
> Only send snippets for completion when client supports it

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/actions/notifications.rs
- src/actions/requests.rs
- src/cmd.rs
- src/lsp_data.rs
- src/server/dispatch.rs
- src/server/io.rs
- src/server/mod.rs
- src/test/mod.rs
https://github.com/gluon-lang/languageserver-types/pull/29 codifies method name and param types in the type system in the same manner as our `Action` trait. This tries to merge those and prepare to update languageserver-types to newer versions.
Most notably this changes implementation from stateful message traits with single-value enums to stateless traits, using uninhabited enums (like in languageserver-types).
Additionally moved back `shut_down` to action context to simplify code and since it makes sense only when server is initialized.
r? @nrc
> Use message traits from languageserver-types

- Cargo.lock
- Cargo.toml
- src/server/mod.rs
Fixes issue described at https://github.com/gluon-lang/languageserver-types/issues/46.
Currently pulls my local branch with backported fix, switching back to crate is blocked both on https://github.com/rust-lang-nursery/rls/pull/658 (updates to newest ls-types) and https://github.com/gluon-lang/languageserver-types/pull/47 (actual fix on top of 0.26).
> Fix Initialized message parsing

- Cargo.lock
- Cargo.toml
- src/actions/notifications.rs
- src/actions/requests.rs
- src/lsp_data.rs
- src/server/dispatch.rs
- src/server/io.rs
- src/server/mod.rs
- src/test/mod.rs
A small followup to #644.
Most notably:
* Uses newly introduced LS types
* Removes `serde_json::to_string(&RequestMessage...` machinery in favor of using new LS traits
*  Consistently uses renamed `Request`, `Notification` as `LSPRequest` and `LSPNotification` to distinguish from our `server::{Request, Notification}` types
r? @nrc
> Update languageserver-types and clean up a bit

- Cargo.lock
- Cargo.toml
Fixes a possible bug from 0.3.5 (https://github.com/rust-lang/rust/pull/47454#issuecomment-358593868) and prepares the RLS repo to be updated in Rust tree.
> Update rustfmt to 0.3.6

- tests/support/mod.rs
- tests/tests.rs
Will avoid timeouts when command tests panic, see https://github.com/rust-lang-nursery/rls/issues/665#issuecomment-358708965
> Handle panics better in command tests

- src/actions/post_build.rs
- src/test/mod.rs
- test_data/compiler_message/consider-borrowing.json
- test_data/compiler_message/mismatched-types.json
- test_data/compiler_message/move-out-of-borrow.json
- test_data/compiler_message/not-mut.json
- test_data/compiler_message/type-annotations-needed.json
- test_data/compiler_message/use-after-move.json
Related to #649, #662 this pr adds `CompilerMessage` secondary `.span` & `.children` information to diagnostics. This really helps the diagnostics in being useful.
_before_
vvv
_before_
vvv
With vscode it cuts off the message mid-word at the max width. Atom wraps properly. I think this is the responsibility of the **client**, as wrapping isn't too arduous. Even so the messages are quite usable in vscode and I'm sure people will appreciate them even cut in half.
I've gone to some pains to avoid showing messages meant for different areas of the code by only including children-spans that are 'within' the primary span and secondary spans that are on the same line. There is some more work for generating additional diagnostics for the other spans.
Since there will be many compiler messages to …
> Add formatted compiler message labels & children to diagnostics

- Cargo.lock
- Cargo.toml
- src/build/rustc.rs
- src/server/mod.rs
Note the diff in Cargo.toml:
```diff
-rls-rustc = "0.1"
+rls-rustc = { git = "https://github.com/nrc/rls-rustc" }
```
Once the new version of rls-rustc is published, this can be restored. 
cc @nrc
> Rustup to rustc 1.25.0-nightly (97520ccb1 2018-01-21)

- Cargo.lock
- Cargo.toml
- src/actions/requests.rs
Panic handler logging only acheives `WARN:rls::actions::requests: Any` so isn't much use, the panic details are already on stderr.
I've added some notes to clarify panic handling. Having the empty panic handler is important, otherwise these would be propagated.
_Note: I also upped _rls-rustc_ -> `0.2.1` to fix compilation._
> Remove panic_handler warn logging

- .travis.yml
How about a compromise for the rarely running osx builds bemoaned in #675? 
This pr still runs osx as before, but `allow_failures` + `fast_finish` mean the travis-build is marked as success as soon as the linux builds have passed. 
So we get the speed of disabling the osx build, but can still inspect the osx build state, logs etc.
> Fix #675 travis allow_failures: osx & fast_finish

- Cargo.lock
- Cargo.toml
Lots of our dependencies are somewhat behind on patch versions. Some of these do affect us, like having env_logger `0.5.3`. I would have thought the lock file was for ensuring one developers experience is the same as anothers & as the release - rather than longer term freezing of dependencies.
If the reason for the lack of wholesale semver-compatible updates is some specific ones we want to carefully control, would it be better to declaratively control these in the _Cargo.toml_ file? 
For this pr I've assumed ***cargo*** is the only such crate & have put a reference to the commit hash we're locked to & updated the rest.
```toml
[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo", rev = "848eb156" }
```
Are they're others we want to control? Or perhaps I am missing a good …
> cargo update, pin "cargo" to 6a8eb71f6

- README.md
The language server protocol documentation has moved.
> Fix link for workspace/DidChangeConfiguration

- src/actions/post_build.rs
- test_data/compiler_message/unused-use.json
Moved the usage of `\n\n` together in the diagnostic messages to avoid cases where they can join together in unexpected ways. Added a regression test for unused `use`.
> Avoid triple-newline in diagnostic messages

- Cargo.lock
- Cargo.toml
cargo git log before...after
```
64f20e4d Fixed relaxed libtest tests
08d48601 Be less strict about loading directory sources
77ccd0e3 Forbid credentials from registry URLs
c40d1836 Fixes for feedback
f6dcdb5c Elaborate registry names to index URLs when publishing
5753e1c0 Remove test that requires Emscripten
5d22cce6 Allow unused_unsafe in LazyCell in preparation for lib change
c4d4012d Add overflow-checks to reference documentation.
c31ad2bc Test sorting of native library paths
f66ac370 Relaxed testing of libtest outputs.
fd4f8410 Link to crate type docs
0d6bc1c1 Remove outdated stability note
0ec7f687 Allow path + registry dependencies
de64f18d Add a missing link in the book for `jobserver`. I don't know what the original intended link destination was...
c85a43b0 Allow packaging of …
```
> Update cargo lib inline with nightly-2018-02-01

- Cargo.lock
- Cargo.toml
- src/build/rustc.rs
cc @killercup
5 internet points for whomever who merges it [before 14:00 UTC Sunday](https://fosdem.org/2018/schedule/event/rust_rustfix_automatic_fixes/)
> Add clippy as an optional feature

- src/actions/post_build.rs
- test_data/compiler_message/cannot-find-type.json
This pr avoids adding notes without content to diagnostic messages.
Note: the _'possible candidates are found in other modules, you can import them into scope'_ help doesn't appear here as it refers to a different span (at the top of the file). We should consider these primary & different span messages, but they shouldn't go into this diagnostic anyway.
> Improve diagnostic formatting: Don't add empty notes

- Cargo.lock
- Cargo.toml
- src/actions/post_build.rs
With https://github.com/rust-lang-nursery/rls/pull/664, clients now receive secondary labels as a single [diagnostic](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#diagnostic).
The issue is that clients don't know to which error belong all the secondary diagnostics.
Adding a `group` field solves this problem.
I intentionally made the minimum and simple changes to the code. Clients are free to ignore the field
I worked a bit with my editor to display the labels and it renders like this:
If this is accepted I will make a PR to [languageserver-types](https://github.com/gluon-lang/languageserver-types)
cc @Xanewok @alexheretic
> Add a "group" field to Diagnostic

- Cargo.lock
- Cargo.toml
- src/actions/post_build.rs
- test_data/compiler_message/clippy-identity-op.json
Adds source **clippy**, rather than **rustc**, when compiler messages include `"rust-clippy"` (the project name part of the clippy more info links).
While this method is fairly crude the chance of labelling an actual **rustc** error as **clippy** seems very low. As such this is definitely an improvement to what we have with little downside. Also since there isn't much code to it we can switch to a better source-detection method easily when one appears.
I've reworked the diagnostic message tests a little to aid source testing along with the new clippy diagnostic formatting regression test.
> Detect clippy diagnostic source

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/actions/requests.rs
- src/actions/work_pool.rs
- src/main.rs
- src/server/dispatch.rs
- src/server/mod.rs
This pr can _help_ #688 by limiting the impact of long running cpu intensive request actions _(racer)_. Currently we limit the tasks hitting the cpu with a thread pool, but work still fills up at a max rate of 1 per request-timeout. If the work can take longer than the request timeout we can build up tasks by slow steady spamming, see https://github.com/rust-lang-nursery/rls/issues/688#issuecomment-363528272. 
Note: this is _still_ possible even though we don't run tasks that have already timed out.
***Related: Really we should have a way to cancel all tasks, that way we could have a single thread that we cancel on timeout. Bosh. Perhaps we should look into _pthread_cancel_.***
* Record tasks in progress
* Immediately fail tasks when in-progress tasks == max tasks and log-warn
* …
> Address work-pool DoS with long running tasks

- README.md
- src/build/cargo.rs
- src/config.rs
- src/test/mod.rs
- test_data/bin_lib/tests/tests.rs
Hello!
This PR is a timid attempt to introduce usage of `all-targets` cargo flag to analyse integration tests under `tests` directory.
Sorry about my poor English.
> Fix #191 check tests directory via 'all-targets' cargo flag

- Cargo.lock
- Cargo.toml
- src/actions/post_build.rs
- test_data/compiler_message/clippy-const-static-lifetime.json
I've been adding CodeAction support to ide-rust today, so now I can actually see the suggestions :). I think they can be improved. This pr tries to do so adding the following changes:
* Support secondary suggestions
* Simplify/shorten formatting. As in practice the compiler messages seemed too long. Instead of ***$long_compiler_message \`$code\`*** we get either
- ***Add \`$code\`*** when suggestion is purely additive, or ***Change to \`$code\`***
- In the case the suggestion is for another line ***Line $line: Add \`$code\`*** or ***Line $line: Change to \`$code\`***
* Upgrade label _"consider changing this to \`code\`"_ to suggestion (for example `v` -> `mut v` suggestion)
* Add unit tests
* Add clippy suggestion unit test
Although not a massive change, I'd appreciate testing in other …
> Improve suggestions

- src/actions/post_build.rs
- src/actions/progress.rs
- src/build/cargo.rs
This is based off #653 and needs to land after that.
Currently build errors go to the logs, but does not show up in the UI. This PR fixes that so that the first encountered build error will be notified using `window/showMessage`. No further build errors will be propagated until the error state has cleared since a build attempt happens on every keystroke.
> Propagate build errors using window/showMessage

- src/actions/requests.rs
- src/lsp_data.rs
This change removes local variables from outline making it much more useful, at least in Atom IDE.
> Removes local variables from outline #594

- README.md
- src/actions/requests.rs
- src/config.rs
Provides manual workaround for #688. Justification is in that thread.
As the default is `true` this change requires manual user configuration to change current behaviour.
I chose `racer_completion` rather than `autocomplete` as the current use case for disabling it is when you care about racer performance edge cases, rather than you don't want autocomplete. But we can rename if something else is better.
> Add `racer_completion` config

- Cargo.lock
- src/actions/post_build.rs
- test_data/compiler_message/unused-use.json
Currently we produce diagnostic by finding the primary span, and using non-primary spans as secondary diagnostics. However, there are cases rustc will return to us multiple primary = true spans & in these we currently ignore this information.
This pr fixes this and treats these following primary spans the same way as we treat non-primary additional diagnostics, but with the severity of `Warning`.
You can commonly see this with multiple unused imports.
**Before**
**After**
> Use multiple primary diagnostics

- Cargo.lock
- Cargo.toml
* Update cargo to https://github.com/rust-lang/cargo/commit/5f83bb4044f32b60d06717c609610f67411fc671 matching nightly-2018-03-14
* Update languageserver-types -> 0.31 (https://github.com/gluon-lang/languageserver-types/commit/f669ada0432768319ad4de2431c2faab34ec61b7 - Adds more `SymbolKind`s, non-breaking for our usage)
* `cargo update`
cargo git log before...after
```
1fd3496a delay calls to `to_inner`
85f96a99 Dependency.name to InternedString
8323081c PackageId.name to InternedString
9b731821 intern links attribute
8f9ada82 restructure `Activations` for better clone
98480e85 use `Deref` instead of an explicit function
827fdf84 use `into_boxed_str` to shrink before we leek
d46db71b Work around #5134 for now
301fccc2 Retain a vector instead of reallocating
26bfc7de add unsafe
06bf6a17 …
```
> Update cargo to match latest nightly

- .travis.yml
Re-purpose the, currently redundant, 2nd Linux run to compile all features (ie `clippy`) + allow failures as we're not too surprised when clippy won't compile after nightly changes.
This run is useful when we're looking at clippy-related prs & tests.
> Add travis --all-features build (clippy)

- src/config.rs
Fixes #730.
If the user did not specify the target dir in the configuration, this will infer this at the initialization and use what Cargo uses instead.
Eventually I think this should be used with `Inferrable` struct, just like with build_* - otherwise a sequence of setting an explicit target dir and 'unsetting' it in the configuration will not correctly run the inference later and it will continue to use the previously set dir.
However, I'm opening it now so I can get more eyes on it and someone can try it out and see if it really works correctly.
> Use Cargo to infer correct target/ build dir

- Cargo.lock
- README.md
- src/actions/notifications.rs
- src/build/rustc.rs
- src/config.rs
New config for clippy
* `clippy_preference` (`String`, defaults to `"opt-in"`) controls eagerness of clippy
diagnostics when available. Valid values are _(case-insensitive)_:
- `"off"` Disable clippy lints.
- `"opt-in"` Clippy lints are shown when crates specify `#![warn(clippy)]`.
- `"on"` Clippy lints enabled for all crates in workspace.
Also
* Warn on config deserialize errors
* cargo update
> Add clippy_preference config

- Cargo.lock
- Cargo.toml
_rust-clippy shortlog_
```
Baelyk (1):
Add suggestion to useless_format
CYBAI (1):
Update configuration for leading dot filename
Karim Snj (2):
while_immutable_condition: fix handling of self
while_immutable_condition: limit suggestion span to condition
Mark Mansi (5):
i128 is stable
i128 is stable
make it pass for now
attempt fix stderr
whitespace
Michael Wright (3):
Minor refactoring (walk_ptrs_ty_depth)
Add tests to ensure that issue #2420 is resolved
Fix enum_glob_use false positives
Oliver Schneider (6):
Use rustc from latest merged PR instead of nightly
undo accidental push to master
Undo a temporary fix for a cargo bug
Update needless_lifetimes_impl_trait.rs
Version bump
Undo current_dir -> CARGO_MANIFEST_DIR move
Philipp Hansch (1):
Fix false positive in …
```
> clippy 0.0.190

- src/build/cargo.rs
- src/config.rs
- src/test/harness.rs
Followup to https://github.com/rust-lang-nursery/rls/pull/788.
First of all, it fixes target/rls dir (with #788 it reused the same dir as Cargo, oops!).
It now uses the `Inferrable` wrapper, so it's possible to specify the value, set it to fallback and then re-set it again.
Additionally it properly uses the relative passed dir (which slipped through in #788, I definitely need to do something about the tests :worried: ) now.
r? @nrc
> Use Inferrable for target/ config option

- Cargo.lock
- src/actions/work_pool.rs
- src/main.rs
- src/server/dispatch.rs
Inspired by the 1.25 release including more `Duration` const fns, I thought we could clarify the usage of `COMPILER_TIMEOUT` which currently seems a little confusing. It's actually just used to define the LSP request-response timeout. Indeed, we _can't_ timeout rustc currently.
I've removed the misleading timeout and added better documentation to `DEFAULT_REQUEST_TIMEOUT`, which is now a const `Duration`.
> Clarify request timeout usage

- Cargo.lock
- Cargo.toml
_shortlog 0.0.190..0.0.191_
```
Benjamin Gill (1):
Delete all code for handling manifest path
Manish Goregaokar (4):
Move RangeArgument
Rustup to rustc 1.26.0-nightly (ae544ee1c 2018-03-29)
Update changelog for 0.191
Bump to 0.191
Oliver Schneider (6):
Implementation + move one lint
Use cargo check instead of cargo rustc
Categorize all the lints!
Update test suite
Document lint groups
Address review comments
```
> Update clippy 0.0.191

- src/build/cargo.rs
- src/test/mod.rs
- test_data/bin_lib/src/lib.rs
- test_data/bin_lib/src/main.rs
Fixes #741.
Fixes #787.
Didn't add a reasonable integration test (like in #741) since the output is very nondeterministic (e.g. sometimes it merges publishDiagnostics from integration test and main crate into a single message, sometimes not etc.).
This basically is equivalent to `cargo check --tests`, which runs the check on every unit test and integration tests.
r? @nrc
> Make cfg_test to match `cargo check --tests`

- Cargo.lock
- Cargo.toml
_git shortlog 311a5..b70ab_
```
Aleksey Kladov (17):
Supply units to the context at the point of creation
Introduce compilation files
Restore --features args for cargo rustdoc
Slightly better variable names
Replace a triple with a struct for readability
Extract target info
Make TargetInfo.cfg private
Rename TargetFileType -> FileFlavor
Move filename logic to FileType
Replace triple with struct
Make assertion more informative
Implement `--out-dir` option
Feature gate `--out-dir`
Test out-dir edge cases
Replace home-grown create_dir_all with std::fs::create_dir_all
Fix tests for mac
Slightly improve InternedString
Alex Crichton (3):
Run `rustc` for information fewer times
Remove rustfmt from Travis
Less aggressively poison sources on builds
Bastien Orivel (1):
Replace tempdir by tempfile …
```
> Update cargo inline with 2018-04-07 nightly

- Cargo.lock
- Cargo.toml
- src/build/cargo.rs
- src/build/plan.rs
This is `master` cargo, which is not at rust-lang/rust yet, but hopefully it'll be there soon!
> Update Cargo to the latest master

- contributing.md
The "good issues to start on" link in `contributing.md` is wrong so I have fixed it.
> Fix incorrect link to "good first issue" label

- src/cmd.rs
The `rootPath` property has been deprecated in favour of `rootUri` so I've updated the code so that the CLI will also send `rootUri` to the language server when initializing it.
> Define rootUri when running rls from the CLI

- Cargo.lock
- src/actions/mod.rs
- src/actions/notifications.rs
- src/server/message.rs
- src/server/mod.rs
- src/test/mod.rs
This pr improves notification handling before an `initialize` request. Currently this improper use causes rls to panic, whereas the spec advises:
> If the server receives a request or notification before the initialize request it should act as follows:
> *   For a request the response should be an error with code: -32002. The message can be picked by the server.
> *   Notifications should be dropped, except for the exit notification. This will allow the exit of a server without an initialize request.
* Pre-initialize notifications are ignored, except `exit`
* Refactored `fn dispatch_message` to use a `match` rather than `if`s to dispatch message handling logic.
* Notifications all expect an `InitActionContext`, rather than `ActionContext` in their handler methods, the `exit` notification …
> Handle pre-initialize notifications

- src/server/dispatch.rs
- src/server/message.rs
- src/server/mod.rs
- src/test/mod.rs
Similar to #853 implementing pre `initialize` **requests** by returning an error response instead of panicking.
* pre-initialize requests return `code: -32002` error responses and rls continues running
* successive `initialize` requests also receive an error response instead of panicking
> Handle pre-initialize requests

- src/main.rs
- src/server/message.rs
- src/test/harness.rs
- src/test/mod.rs
Also allow _too_many_arguments_
This pr is in honour of rls-clippy actually working with this morning's new rust release.
> Fix clippy suggestions

- README.md
- src/build/cargo.rs
- src/build/mod.rs
- src/config.rs
- src/test/mod.rs
- tests/tests.rs
r? @Xanewok 
Discussed in https://github.com/rust-lang-nursery/rls/issues/132
> Remove workspace mode, change some options

- src/cmd.rs
Also made `help` use a single multi-line string. It's neat and _might_ stop random server output interspersing the help output.
> Add 'document' CLI command (textDocument/documentSymbol)

- src/server/io.rs
1. `cargo test`
2. Change LangaugeClient-neovim to output messages with `Content-Type`. Verified works.
> Support cases there are headers other than `Content-Length`.

- src/server/message.rs
- src/server/mod.rs
Regressed in #856 where I unified/simplified `BlockingRequestAction`s to return their responses. In the `initialize` case though I missed that the early response was intended.
This functionality is restored in this pr, but keeping the improved error handling of #856 & with a comment to help avoid the same mistake.
Fixes #863
> Ensure initialize response is sent before `ctx.init`

- Cargo.lock
- Cargo.toml
- src/build/rustc.rs
RLS is broken by https://github.com/rust-lang/rust/pull/50615 and https://github.com/nrc/rls-rustc/pull/8 is also required to merge this
> Update to rustc master

- contributing.md
I tried building rls project on new ubuntu 16.04 (ubuntu/xenial64
vagrant), but it failed with a message::
Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
After installing this package using apt-get, `cargo build --release`
finished successfully.
Full error message below:
error: failed to run custom build command for `openssl-sys v0.9.31`
process didn't exit successfully: `/home/vagrant/rls/target/release/build/openssl-sys-71380b530539df2a/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR …
> Add missing dev openssl package in contributing.md.

- Cargo.lock
- Cargo.toml
- src/cmd.rs
* Reported in #838, also related: https://github.com/rust-lang/rust/issues/42869
* Update rustfmt -> 3d85084a
> cli: Workaround UNC path fs::canonicalize return

- Cargo.lock
- Cargo.toml
- src/actions/diagnostics.rs
- test_data/compiler_message/macro-error-no-trait.json
Produce useful diagnostics from macro messages. 
Previously the file reference for macro diagnostics were coming out as something like `./<vec macros>`. This meant the error doesn't properly show up at the site in source, and suggestions are not usable.
```rust
fn main() {
let mut out = String::new();
write!(out, "{}", 123);
}
```
This is quite annoying in large code bases, where is this error?!
Resolves #183
Resolves #638
> Handle macro error diagnostics

- src/actions/notifications.rs
- src/actions/requests.rs
- src/cmd.rs
- src/server/io.rs
- src/server/message.rs
- src/server/mod.rs
- src/test/harness.rs
- src/test/mod.rs
This change introduces RequestId type that represents either numeric or string id, and replaces use of usize with this newly introduced type.
> Support string request ids.

- contributing.md
- Describe how to use rls-vscode with custom RLS binaries
- Clarify how to access stderr in vscode. HIDE_WINDOW_OUTPUT is no
longer a thing.
- CLI mode now needs explicit --cli flag, not just any argument
> Minor clarifications in contributing.md

- src/server/io.rs
Fixes include:
- allow headers in different order (content-length doesn't have to be
first)
- fix infinite loop when stdin ended in the middle of the header
> Add unit tests to MessageReader and small fixes.

- src/cmd.rs
- src/server/io.rs
Both of the id generation methods we use are a bit odd. The main one uses an `AtomicU32` then cast to a `u64`. The cli uses a mutable static `u64` with an unsafe block, I'm sure it's fine with the single-thread usage, _but still_. 
...`AtomicU64` to the rescue!
> Use AtomicU64 ids

- Cargo.lock
- Cargo.toml
- src/build/rustc.rs
Compilation with the clippy feature broke probably with 7d0bc550b0899a13a56c81eb2d5064abd0bcf385.
Update clippy_lints to 0.0.207
> Fix compilation with clippy feature

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/actions/requests.rs
- src/actions/run.rs
- src/lsp_data.rs
- src/main.rs
- src/server/dispatch.rs
- src/server/mod.rs
- src/test/lens.rs
- src/test/mod.rs
- test_data/lens_run/Cargo.lock
- test_data/lens_run/Cargo.toml
- test_data/lens_run/src/main.rs
For https://github.com/rust-lang-nursery/rls-vscode/pull/347
> CodeLens support

- bors.toml
Hi! What do you feel about adding https://bors.tech/, an as-a-service version of Rust's bors?
I think it can help a little with timezones challenges and reduce the number of sun round trips required to merge a PR. For example, https://github.com/rust-lang-nursery/rls/pull/919#issuecomment-401238615 perhaps could've made use of `bors delegate+` feature to implement "changes look good to me, but there's a trivial merge conflict. Feel free to self-r+ once the the conflict is fixed".
bors.tech is being used by [crates.io](https://github.com/rust-lang/crates.io) and [IntelliJ Rust](https://github.com/intellij-rust/intellij-rust).
Oh, and the not rocket science rule is good in and of itself :D
> The last of the masters

- Cargo.lock
- Cargo.toml
- src/actions/requests.rs
The RLS side of https://github.com/nrc/rls-analysis/pull/141
> Better symbol search

- Cargo.lock
- Cargo.toml
* Update cargo inline with nightly
* `cargo update` dependencies for a slew of semver updates
```
Updating aho-corasick v0.6.4 -> v0.6.5
Updating backtrace v0.3.8 -> v0.3.9
Updating cargo_metadata v0.5.4 -> v0.5.8
Updating cfg-if v0.1.3 -> v0.1.4
Updating clap v2.31.2 -> v2.32.0
Updating dtoa v0.4.2 -> v0.4.3
Updating futures v0.1.21 -> v0.1.22
Updating getopts v0.2.17 -> v0.2.18
Updating git2 v0.7.1 -> v0.7.2
Updating idna v0.1.4 -> v0.1.5
Updating itoa v0.4.1 -> v0.4.2
Updating libc v0.2.41 -> v0.2.42
Updating libgit2-sys v0.7.2 -> v0.7.4
Updating log v0.4.1 -> v0.4.3
Updating num-traits v0.2.4 -> v0.2.5
Updating openssl v0.10.8 -> v0.10.10
Updating openssl-sys v0.9.31 -> v0.9.33
Updating proc-macro2 v0.4.4 -> v0.4.6
Updating redox_syscall v0.1.38 -> v0.1.40
Updating regex v1.0.0 -> …
```
> Update cargo -> af9e40

- Cargo.lock
- Cargo.toml
- src/actions/requests.rs
- src/lsp_data.rs
- src/server/dispatch.rs
- src/server/mod.rs
- src/test/mod.rs
This PR removes the custom `FindImpls` method and replaces it with the standard `GotoImplementation` method from version [3.6.0](https://microsoft.github.io/language-server-protocol/specification#version_3_6_0) of the LSP.
> Switch to standard implementation method.

- src/main.rs
> Fix stack overflow on windows.

- Cargo.toml
- src/actions/diagnostics.rs
- src/actions/mod.rs
- src/actions/notifications.rs
- src/actions/post_build.rs
- src/actions/progress.rs
- src/actions/requests.rs
- src/actions/run.rs
- src/actions/work_pool.rs
- src/build/cargo.rs
- src/build/mod.rs
- src/build/plan.rs
- src/build/rustc.rs
- src/cmd.rs
- src/config.rs
- src/lsp_data.rs
- src/main.rs
- src/server/dispatch.rs
- src/server/io.rs
- src/server/message.rs
- src/server/mod.rs
- src/test/harness.rs
- src/test/mod.rs
- tests/support/mod.rs
- tests/tests.rs
While `dyn` fixing annotations was straightforward, doing that for urneachable_pub was awkward... Not sure I agree with most of the changes - IMO `pub(crate)` adds more noise and regular `pub` should be treated as such, especially for bin targets, but that may be just me. Tried to go for the most restrictive visibility for the warned against items (not sure if that's good).
r? @nrc
> Prepare for 2018 edition

- Cargo.lock
- Cargo.toml
> :arrow_up: clippy

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/actions/post_build.rs
- src/build/mod.rs
- src/concurrency.rs
- src/main.rs
- src/server/dispatch.rs
- src/server/message.rs
- src/server/mod.rs
- src/test/harness.rs
- src/test/lens.rs
- src/test/mod.rs
Hi!
In tests, we currently do synchronization via `thread::sleep`. It is rather problematic by itself, but it also shows that we don't have a very good control of concurrency inside RLS :( 
I think this is a big problem: RLS is going to be a highly concurrent application, so it's better to establish reliable concurrency practices from the start. I don't have too much experience with designing concurrent though, so I am not sure if the proposed approach of dealing with the problem is not insane :D 
In my experience, a lot of problems with managing concurrency stem from "fire an forget" approach: if a function schedules some work to be executed outside the dynamic extent of the function call itself (for example, by spawning a thread, or by submitting the work to some queue), and doesn't …
> Managed concurrency

- .travis.yml
- appveyor.yml
We should exclude the staging.tmp branch from CI according to
https://bors.tech/documentation/getting-started/
> Don't build bors .tmp branch

- src/actions/requests.rs
- src/test/harness.rs
- src/test/lens.rs
- src/test/mod.rs
- test_data/workspace_symbol_duplicates/Cargo.lock
- test_data/workspace_symbol_duplicates/Cargo.toml
- test_data/workspace_symbol_duplicates/src/main.rs
- test_data/workspace_symbol_duplicates/src/shared.rs
Sometimes analysis returns duplicate symbols for the same location. It
can be a bug in the analysis, however in general it might be the case
that two logically different symbols correspond to the same location,
if we use `include!` or something like that.
So, let's do duplicate detection before submitting results to the user
for the time being
closes https://github.com/rust-lang-nursery/rls/issues/922
Here's an example of the problem happening in the real life, without `#[path="..."]` tricks:
Ideally, we should fix ^ directly, but I don't know what exactly is the problem.
> Filter out duplicate symbols

- .gitignore
- src/test/lens.rs
- test_data/Cargo.toml
cc https://github.com/rust-lang/rust/pull/42146
closes https://github.com/rust-lang-nursery/rls/issues/925
After this, we could and should eliminate https://github.com/rust-lang/rust/blob/4260c8b1e4b273facf1072b9457dfaedd7f03f3e/src/Cargo.toml#L26-L40
> Make the workspace hack local to RLS

- src/actions/requests.rs
- Filter out symbols with their ranges having the equal start and end positions
> Issue #939 - DocumentSymbol sending arg0

- Cargo.lock
- Cargo.toml
Notably, this includes
https://github.com/crossbeam-rs/crossbeam-channel/commit/591d3165f8e8892023500cd31195be7949f2235d,
which is a fix for unsoundness we've actually hit in RLS!
supersedes https://github.com/rust-lang-nursery/rls/pull/951
> :arrow_up: crossbeam-channel

- src/actions/progress.rs
- src/actions/run.rs
- src/actions/work_pool.rs
- src/build/cargo.rs
- src/build/environment.rs
- src/build/plan.rs
- src/build/rustc.rs
- src/config.rs
- src/lsp_data.rs
- src/main.rs
- src/server/message.rs
- src/test/harness.rs
- Ran cargo fix to add '_ lifetimes
- removed #[macro_use] statements for failure & lazy_static
I stopped at
```rust
#[macro_use]
extern crate log;
```
It seems a bit painful to have to import the log macros at each use. So I'll leave the more problematic ones for now, maybe there is, or will be, a better option?
> Fix some edition issues

- src/actions/post_build.rs
It took me quite some time to figure out why `Ctrl+T > finalize` was not finding this :)
> use US spelling

- Cargo.lock
- Cargo.toml
- src/test/mod.rs
I found out _serde_json_ can do the dynamic stuff like the _json_ crate. So we may as well use that as it's already a dependency.
Also
* cargo update
* remove erroneous comment on `src/test/mod.rs` as every test in this file tests the rls.
```rust
// Utilities and infrastructure for testing. Tests in this module test the
// testing infrastructure *not* the RLS.
```
> Remove json dependency & use serde_json

- src/actions/diagnostics.rs
- src/actions/mod.rs
- src/actions/notifications.rs
- src/actions/post_build.rs
- src/actions/requests.rs
- src/actions/run.rs
- src/actions/work_pool.rs
- src/build/cargo.rs
- src/build/mod.rs
- src/build/plan.rs
- src/build/rustc.rs
- src/concurrency.rs
- src/config.rs
- src/lsp_data.rs
- src/main.rs
- src/server/dispatch.rs
- src/server/io.rs
- src/server/message.rs
- src/server/mod.rs
Fixed all `rust_2018_idioms` lints. 
(Because we compile the tools with `-D warnings` in the rustc repository, all lints have to be fixed 🤷)
> Import macros using `use` statements instead `#[macro_use]`.

- src/test/harness.rs
When the RLS source is mounted on a read-only drive, the test_data tests will all fail because `cargo` cannot write `Cargo.lock`. We allow caller to copy the `test_data` directory to a read-write location, and use `$RLS_TEST_WORKSPACE_DIR` to refer to the directory containing `test_data` to allow the tests to pass.
```
$RLS_TEST_WORKSPACE_DIR/     (default to $PWD)
test_data/
Cargo.toml
Cargo.lock           (generated)
bin_lib/
...
...
target/                  (generated, if $CARGO_TARGET_DIR is undefined)
tests/
0/
...
...
```
> Allow harnessing from other than `$PWD/test_data`.

- test_data/reformat/rustfmt.toml
- test_data/reformat_with_range/rustfmt.toml
The latest rustfmt includes rust-lang-nursery/rustfmt#2823 which changed the default line ending from `"Unix"` to `"Native"`. This breaks our test cases on Windows which still expected `\n` line endings. Rather than duplicating the test results for both Windows (`\r\n`) and elsewhere (`\n`), I configure rustfmt to always emit Unix (`\n`) line ending. This also insulates us from any future new decision from rust-lang-nursery/rustfmt#2846.
> Require "Unix" newline style everywhere in reformat tests

- Cargo.lock
- Cargo.toml
- src/actions/requests.rs
That way, we don't need to maintain racer version in VFS.
Right now, for example, I can't say `racer = { path = "../racer" }` in `rls/Cargo.toml`, b/c that won't be the same racer that rls_vfs usues. But given that the amount of code in question is tiny, it seems operationally more effective to just write a newtype wrapper inside rls.
> Move vfs-racer impls to RLS

- Cargo.lock
- Cargo.toml
- src/build/cargo.rs
Found as part of rust-lang/rust#52919
> Update to the latest Cargo

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/build/plan.rs
- src/build/rustc.rs
- src/server/message.rs
- cargo -> `6a7672`
- cargo_metadata -> `0.6`
- clippy -> `07c2e6`
- cargo update
```
Updating backtrace-sys v0.1.23 -> v0.1.24
Updating cfg-if v0.1.4 -> v0.1.5
Updating cmake v0.1.31 -> v0.1.33
Updating env_logger v0.5.11 -> v0.5.12
Updating lazy_static v1.0.2 -> v1.1.0
Updating libc v0.2.42 -> v0.2.43
Updating libz-sys v1.0.18 -> v1.0.20
Updating openssl v0.10.10 -> v0.10.11
Updating openssl-sys v0.9.33 -> v0.9.35
Updating pkg-config v0.3.12 -> v0.3.13
Updating proc-macro2 v0.4.9 -> v0.4.12
Updating quote v0.6.4 -> v0.6.6
Updating rand v0.5.4 -> v0.5.5
Updating rustc_version v0.2.2 -> v0.2.3
Updating serde v1.0.70 -> v1.0.71
Updating serde_derive v1.0.70 -> v1.0.71
Updating serde_json v1.0.24 -> v1.0.26
Updating smallvec v0.6.3 -> v0.6.4
Updating syn v0.14.6 -> v0.14.8
Updating …
```
> Update dependencies & fix

- src/test/harness.rs
- src/test/lens.rs
- src/test/mod.rs
This PR adds three functions to the test harness, essentially replacing `expect_messages`. Most notably operations are now done on a message-by-message basis, clearing valid messages from the buffer.
* `soft_expect_message` checks if a message matches the expectation and returns an `Err` if not
* `expect_message` is a `panic!` wrapper around `soft_expect_message`, which is not public
* `expect_fuzzy` (name to be :bike::house:) soft_checks for messages until they no longer match the expectation.
Things that are left to do
> [WIP] Refactoring test harness

- Cargo.lock
- Cargo.toml
- src/main.rs
update clippy_lints git dependency to f05a1038b59cd4217e58b3aef7a0751a0efd01e4
hopefully this fixes rls build with latest rustc master, and, once rls is submodule is updated in the rustc repo, the broken rustc rls toolstate.
> deps: update clippy_lints git dependency

- Cargo.lock
- Cargo.toml
Another clippy_lints update for latest clippy breakage.
> update clippy_lints to e9c3d3d50261b9cc6143dc02885cda265e926d30

- Cargo.lock
- Cargo.toml
This should fix RLS toolstate in Rust master, see
https://github.com/rust-lang/rust/pull/53638#issuecomment-415547528
for more details.
> Bump clippy (for Rust repo)

- Cargo.lock
- Cargo.toml
- src/actions/format.rs
- src/actions/hover.rs
- src/actions/mod.rs
- src/actions/requests.rs
- src/config.rs
Fixes #812. (Uses https://github.com/Xanewok/rustfmt/tree/file-lines-ser-json)
High-level overview:
* Introduces `trait Formatter { fn format(&self, String, rustfmt::Config) -> Result<String, String>; }`
* Introduces a `Rustfmt` enum as a convenient interface which implements the trait, accessible via `ctx.formatter()`
* `Rustfmt::Internal` variant implementation is what was currently used, running included Rustfmt in-process
* `Rustfmt::External` spawns the provided command, using the Rustfmt stdin/stdout mode.
Assuming that Rust input should be a valid UTF-8 and so Rustfmt should also reformat it to a valid UTF-8, returning `Err` if that's not the case.
This is not entirely correct yet, since we should pass full Config in a file to executed Rustfmt, since LSP may request additional …
> Support using external Rustfmt

- Cargo.lock
- Cargo.toml
- src/project_model.rs
- tests/tests.rs
> Allow project model to download crates

- Cargo.lock
- Cargo.toml
* Fix clippy compile
* Update cargo to nightly version
* cargo update
```
Updating aho-corasick v0.6.6 -> v0.6.8
Updating bitflags v1.0.3 -> v1.0.4
Updating byteorder v1.2.4 -> v1.2.6
Updating cc v1.0.18 -> v1.0.22
Updating env_logger v0.5.12 -> v0.5.13
Updating fst v0.3.0 -> v0.3.1
Updating log v0.4.3 -> v0.4.4
Updating matches v0.1.7 -> v0.1.8
Updating memchr v2.0.1 -> v2.0.2
Updating miow v0.3.1 -> v0.3.3
Updating parking_lot_core v0.2.14 -> v0.2.15
Updating pkg-config v0.3.13 -> v0.3.14
Updating proc-macro2 v0.4.12 -> v0.4.15
Updating quote v0.6.6 -> v0.6.8
Updating rand v0.4.2 -> v0.4.3
Updating regex v1.0.2 -> v1.0.4
Updating ryu v0.2.3 -> v0.2.6
Updating same-file v1.0.2 -> v1.0.3
Updating serde v1.0.71 -> v1.0.75
Updating serde_derive v1.0.71 -> v1.0.75
Updating syn v0.14.8 -> …
```
> clippy -> d99cea, cargo -> 0ec728

- README.md
This uses awesome dynamic shields from https://shields.io and queries https://raw.githubusercontent.com/rust-lang-nursery/rust-toolstate/master/_data/latest.json tracked by our awesome [rust-toolstate](https://rust-lang-nursery.github.io/rust-toolstate/) bot.
[Rendered](https://github.com/Xanewok/rls/tree/nightly-shields)
The queries are currently `$[2].windows` and `$[2].linux` (jsonpath) respectively, because the data is an array of objects and RLS tool currently happens to be the 3rd one on the list.
@kennytm hopefully this info in README.md shouldn't be useful for too long (because we might want to block nightlies again on RLS fail etc.) but do you think it might be a good idea to change the data format to an object with tool keys `{ "rls": {...}, "clippy": {...}, ... }` to facilitate …
> Add rust-toolstate shields to README.md

- Cargo.lock
- Cargo.toml
- src/build/external.rs
- src/build/mod.rs
- src/config.rs
@nrc this is the implementation of external build we talked about.
What's left is resolving the timeout issue (otherwise RLS will be stuck waiting 'building' if the build command loops) and resolving the pathbuf (de)serialize in rls-data (rustc serializes it with rustc-serialize, added a Deserialize impl for Serde backend deserializing with rustc-serialize format).
Since I worked on integrating this with Buck, here's a simple script that I used:
```bash
#!/bin/bash
BUCK=~/repos/buck/bin/buck
RULE=$("$BUCK" query "owner($1)")
DEPS=$("$BUCK" query "kind('^rust_.*$', deps($RULE))")
for dep in $DEPS; do
$BUCK build "$dep#save-analysis" --show-output | awk '{print $2}'
done
```
which for `"rust.build_command": "/home/xanewok/.../script.sh server/src/main.rs`, for example, outputs:
``` …
```
> Support simple external builds

- src/build/rustc.rs
Despite recent Clippy bump in Rust, the current master doesn't compile because `clippy_lints::Conf` is private. Changed this to `clippy_lints::read_conf` like in clippy's analogous [driver.rs](https://github.com/rust-lang-nursery/rust-clippy/blob/c81d70e6bdf264c62136b571760f152be9638ec0/src/driver.rs#L102).
I believe this should detect clippy.toml on the filesystem level and the TODO comment can be removed @oli-obk @alexheretic 
Will try to pull this in https://github.com/rust-lang/rust/pull/53870 to see if RLS is fixed for the next nightlies.
cc @nrc
> Compile with newest rustc master

- src/server/mod.rs
Avoids needing to trace log to pull out an offending json request. Will help with issues like #1038
> Include message in dispatch error log line

- src/server/message.rs
- src/server/mod.rs
This change moves to permissive deserialisation of request void-params. Currently if a client sends a requests with non-null params, ie a `{}`, we error. But in the case the params end up as `()` we're better served just continuing.
Technically this was actually more of a pain than it seemed. With our use of generics it's not easy to tell if params _are_ `()`. Without specialisation I can't add an additional implementation for void param requests.
Instead I used `size_of<R::Params> == 0` to deduce that the params are void-type and put in a workaround.
Fixes #1038
> Avoid void-params deserialize errors

- src/actions/format.rs
Fix 
```
warning: use of deprecated item 'rand::Rng::gen_ascii_chars': use sample_iter(&Alphanumeric) instead
--> src/actions/format.rs:120:39
|
120 |     let suffix: String = thread_rng().gen_ascii_chars().take(SUFFIX_LEN).collect();
|                                       ^^^^^^^^^^^^^^^
|
= note: #[warn(deprecated)] on by default
```
> Fix duplicated warning for rand::Rng::gen_ascii_chars

- src/main.rs
Needed to fix https://github.com/rust-lang/rust/pull/54057
> enable crate_visibility_modifier since it is used but no longer part of 2018 edition.

- src/build/mod.rs
See https://github.com/rust-lang/rust/pull/54011#issuecomment-419828892 for the ambiguity error being fixed.
> Future-proof for #![feature(uniform_paths)].

- Cargo.lock
- Cargo.toml
- src/build/rustc.rs
See rust-lang/rust#53166 (comment) for the decision. Needed for rust-lang/rust#54116.
> Reintroduce `extern crate` for non-Cargo dependencies.

- Cargo.toml
Gets rid of the 
```
warning: the cargo feature `edition` is now stable and is no longer necessary to be listed in the manifest
```
warning message.
> Remove "edition" Cargo feature (it's stable now)

- Cargo.lock
- Cargo.toml
- src/project_model.rs
Fixes the fallout of rust-lang/rust#54334
> Update Cargo in the RLS

- Cargo.toml
This reverts commit a34334dcdd291f4fc42cd910a098a95f1f53a4a2.
The problem is that rustc uses an older cargo version to bootstrap.
This cargo version does not have the edition feature stabilized yet.
Clippy also had this problem.
cc @Xanewok
> Revert "Remove "edition" Cargo feature (it's stable now)"

- src/build/cargo.rs
- src/build/plan.rs
Currently you get your crates cropping up a couple of times in the build progress messages. The 2nd time is building the crate with `cfg(test)`. This change helps make that clear.
Using [glyph-brush](https://github.com/alexheretic/glyph-brush) as an example:
```
window/progress {id: "progress_1", title: "Building"}
window/progress {id: "progress_1", message: "glyph_brush_layout", title: "Building"}
window/progress {id: "progress_1", message: "glyph_brush_layout", title: "Building"}
window/progress {id: "progress_1", message: "glyph_brush", title: "Building"}
window/progress {id: "progress_1", message: "glyph_brush", title: "Building"}
window/progress {id: "progress_1", message: "gfx_glyph", title: "Building"}
window/progress {id: "progress_1", message: "gfx_glyph", title: "Building"} …
```
> Indicate a cfg(test) build in window/progress messages

- tests/support/mod.rs
- tests/support/paths.rs
- tests/tests.rs
* Rewrite all _tests/tests.rs_ "cmd" tests
* <s>cargo update</s>
* cmd test wait-for-rls-stdout timeout reduced 300 -> 30
The cmd tests aren't good enough because they don't fail very usefully. They either work or block for 300 seconds then say nothing. For example the build is currently failing in master, but can anyone see why?
The new code has
* Explicit timeouts for any blocking calls, meaning it's easy to see where we wait for stdout.
* More accurate dynamic json assertions. 
```rust
assert_eq!(json["method"], "window/progress");
assert_eq!(json["params"]["title"], "Indexing");
```
* Removed all but one test checking _window/progress_ messages.
* Removed outer timeout/closure which obfuscates test panics & adds complexity.
The `RlsHandle` now uses a thread to eagerly read stdout, and …
> Rework cmd tests

- Cargo.lock
- Cargo.toml
- README.md
- src/build/mod.rs
- src/config.rs
* Record last build duration, use this to infer an appropriate build debounce time using:
| Last build time | wait_to_build |
| -- | -- |
| < 300ms | 0ms |
| < 1 second | 200ms |
| < 5 seconds | 500ms |
| >= 5 seconds | 1500ms |
* Add info build duration logging, also indicating if the build was a cargo or rustc run.
This gives a nice reduction in the _time to diagnostics_ for small & medium projects while having no impact on large projects where the wait_to_build will end up unchanged at 1.5s. Also client's setting this config will have rls function as before, overriding any tuning behaviour.
It actually has a natural positive impact on the longer tests too, we never set a wait_to_build there (doh!). Though remember wait_to_build only affects the rustc builds subsequent to the initial …
> Automatically tune wait_to_build

- Cargo.toml
Minus and minus equal plus, I guess :man_shrugging:
> Revert "Revert "Remove "edition" Cargo feature (it's stable now)""

- .travis.yml
- Cargo.lock
- Cargo.toml
- appveyor.yml
- tests/support/mod.rs
- tests/tests.rs
This change attempts to have cmd test timeouts indicate more confidently that something went wrong, rather than just the test runner was running slowly.
Along with recording stdout from rls we now also record the instant of the last stdout write. This allows us to measure timeout duration from call time **or** last stdout write time (whichever is smaller).
This helps eliminates the niggling possibility that the timeout was just a little too small, and rls was writing stuff but just hadn't got to the point we expected yet, as rls would have definitely written nothing for an entire timeout duration without other interaction.
So a timeout error looks like this: 
```
thread 'cmd_test_complete_self_crate_name' panicked at 'Timed out waiting 30s for predicate, last rls-stdout write 30.0s ago', …
```
> Improve cmd test timeout reliability

- .travis.yml
- appveyor.yml
- src/actions/post_build.rs
- src/build/cargo.rs
- src/build/mod.rs
- tests/support/mod.rs
- tests/tests.rs
Instead of handling some cargo errors with the message _"Error compiling dependent crate"_ we'll now propagate the cargo error and create a root manifest diagnostic with full causal details of it.
* Having cargo error details helps users figure out why the build is failing, as highlighted in #1069
* Using a diagnostic allows us more space to write the full error, as well as avoiding spam issues with _showMessage_. Cargo error diagnostics fit in with the other diagnostics.
* We create a single diagnostic covering the entire of the root manifest. So an issue with a certain dependency isn't very accurately targeted currently as the whole manifest is flagged. More accurate locations are not currently included in cargo errors, though we may be able to infer them.
* We use the root manifest …
> Propagate cargo errors as manifest diagnostics

- src/actions/hover.rs
- test_data/hover/save_data/test_tooltip_mod_use_external.rs.0014_012.json
- test_data/hover/save_data/test_tooltip_mod_use_external.rs.0015_012.json
Fixes hover failing `std::sync` tests after doc change. I also added _starts_with_ testing support, rather than full equality testing which will make the tests a little less fragile.
> Fix std::sync hover doc expectation

- Cargo.lock
- Cargo.toml
- src/actions/post_build.rs
- tests/tests.rs
This is a follow up to #1079 introducing diagnostic positioning for toml parse errors.
This is possible as these errors already include a `toml::de::Error::line_col` method.
As in #1079 we're still assuming root manifest, so if the toml error is from a child manifest in the workspace this error will be misleading. However, perhaps no more misleading than one covering the entire of the root manifest.
> Detect manifest diagnostic position for toml::de::Error

- src/actions/post_build.rs
- src/build/cargo.rs
- src/build/cargo_plan.rs
- src/build/external.rs
- src/build/mod.rs
- src/build/plan.rs
- src/build/rustc.rs
- src/config.rs
From the commit description:
This adds a `BuildGraph` trait which aims to abstract away the API for
a build plan and it implements it for the in-process Cargo build plan
as well as the new, external one (for `cargo build --build-plan`
format).
In addition to that, since save-analysis (since rls-data 0.18.1)
includes the invocation used to compile a given crate, we try to
recreate the external build plan from the passed save-analysis files
via `build_command` config option.
This is squashed into a single commit not to miss anything during the rebase and because my branch diverged from head a bit and kept going back and forth; hopefully this will be legible.
TL;DR:
* Moved `plan.rs` -> `cargo_plan.rs`
* Added external build plan format (like in `cargo build --build-plan`)
* Added and …
> Implement external build plan

- src/actions/hover.rs
- test_data/hover/src/test_extract_docs_comment_first_line.rs
Fixes #1086 and possibly #1016
> Fixes an edge case where doc extraction resulted in an infinite loop

- src/actions/hover.rs
Also corrected some of the trace wording that was no longer accurate after the changes in PR #1088.
This PR is to help track down if doc extraction is the culprit in the excessive CPU usage issue: #1016.
> Add addtional trace logging in hover doc extraction

- Cargo.lock
- Cargo.toml
- src/actions/post_build.rs
- src/build/cargo.rs
- src/build/mod.rs
- tests/tests.rs
Following #1079 and https://github.com/rust-lang/cargo/pull/6157 we can use cargo `ManifestError` chains & `ResolveError`s to discern a more precise manifest in the workspace to highlight as erroneous.
This means things like toml parse errors in a member manifest will be correctly targeted in a diagnostic.
I've also added `ResolveError` support following the https://github.com/rust-lang/cargo/pull/6175 merge. This allows us to find a member manifest when reporting dependency resolution errors during workspace compilation.
* cargo & clippy updated inline with current rust-lang/rust submodules _(required for new cargo functionality)_
* cargo update
> Use ManifestError & ResolveError APIs to highlight workspace member Cargo.toml errors

- src/actions/hover.rs
- src/actions/progress.rs
- src/actions/requests.rs
- src/build/rustc.rs
- src/config.rs
It is annoying that RLS deglobs imports in different order from rustfmt. This PR changes deglob's ordering to rustfmt-like one.
> Use rustfmt-like sort in deglob

- tests/support/mod.rs
- tests/tests.rs
We're still not fully reliable in CI, in particular the "cmd_" tests. This change adds completion request retrying if we get back empty results to work around a race for rls to be ready to return the completions. It also adds a pattern of waiting on response-id rather than expectation, which should reduce the chances of timeout in favour of fast-failing.
```
---rls-stdout---
failures:
---- cmd_test_complete_self_crate_name stdout ----
thread 'cmd_test_complete_self_crate_name' panicked at 'Timed out waiting 300s for predicate, last rls-stdout write 300.0s ago', tests\support\mod.rs:163:13
stack backtrace:
0: std::sys::windows::backtrace::set_frames
...rest of stack trace...
---rls-stdout---
Content-Length: 605
{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverPro …
```
> Ci testing: Retry completions on empty response

- Cargo.lock
- Cargo.toml
Those dependencies required no code changes for update. The changes
are:
- rls-vfs: 0.4.6 -> 0.6.0
- url: 1.1.0 -> 1.7.1
- walkdir: 2.1 -> 2.2.5
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
> Bump dependencies that are compatible

- Cargo.lock
- Cargo.toml
- src/actions/notifications.rs
- src/actions/requests.rs
- src/lsp_data.rs
- tests/tests.rs
~Blocked on https://github.com/nrc/rls-vfs/pull/24.~
Fixes #1104.
r? @nrc
> Fix crashes when editing wide characters spanning 2 `u16`s (UTF-16)

- src/actions/mod.rs
- src/actions/post_build.rs
- src/actions/requests.rs
- src/build/cargo.rs
- src/build/cargo_plan.rs
- src/build/external.rs
- src/build/mod.rs
- src/build/plan.rs
- src/build/rustc.rs
> Collect input files for crates

- Cargo.lock
- Cargo.toml
- src/actions/hover.rs
- src/lsp_data.rs
- src/project_model.rs
~Needs a Racer release including the https://github.com/racer-rust/racer/pull/1000~
cc @kngwyu 
@nrc this has the remaining impls. Still fails on:
```
failures:
---- test::test_goto_def stdout ----
thread 'test::test_goto_def' panicked at 'Assert failed: Could not find `"start":{"line":20,"character":8}` in `{"jsonrpc":"2.0","id":11,"result":[]}`', src/test/harness.rs:227:9
---- test::test_hover stdout ----
thread 'test::test_hover' panicked at 'Assert failed: Could not find `[{"language":"rust","value":"&str"},{"language":"rust","value":"let world = \"world\";"}]` in `{"jsonrpc":"2.0","id":11,"result":{"contents":[]}}`', src/test/harness.rs:227:9
---- test::test_highlight stdout ----
thread 'test::test_highlight' panicked at 'Assert failed: Could not find …
```
> Update Racer and Rustfmt

- tests/tests.rs
https://github.com/rust-lang/rust/pull/56061?#issuecomment-440200208
> Fix `cmd_format_utf16_range` test on Windows

- tests/support/mod.rs
Fixes fallout from https://github.com/rust-lang/rust/pull/53586 (confirmed locally).
> Set the __CARGO_TEST_ROOT env variable for during tests.

- Cargo.lock
- Cargo.toml
Fixes compile & mirrors pr: https://github.com/rust-lang/rust/pull/56136
Also `cargo update` + nursery graduation.
> Update clippy -> 2f6881c6

- src/actions/hover.rs
- src/actions/mod.rs
- src/actions/notifications.rs
- src/config.rs
- src/lsp_data.rs
- src/server/mod.rs
- src/test/harness.rs
- src/test/lens.rs
- src/test/mod.rs
Allows configuration at startup via `initializationOptions.settings` (mirroring _DidChangeConfigurationParams.settings_).
* Removed serialize implementations preferring to test with `json!` (also Config serialize impl wasn't working fully).
* Add warn logging when initialization options fail to deserialize. _Adding unknown options warnings in future would also be nice_.
Resolves #1026
> Support InitializationOptions.settings

- src/test/mod.rs
- test_data/reformat_with_range/rustfmt.toml
Files in checkout have EOL changed from LF to CRLF, see
https://travis-ci.community/t/files-in-checkout-have-eol-changed-from-lf-to-crlf/349.
Now only `test_tooltip` fails with
```
test actions::hover::test::test_tooltip ... FAILED
error: unexpected close delimiter: `}`
--> <stdin>:5:1
|
5 | }
| ^ unexpected close delimiter
```
> Fix reformat_with_range test in CI for Windows

- .travis.yml
It seems our cache pushing takes a wee bit more than 180s, which exceeds the timeout. Bumping it to 300s doesn't add too much time and thanks to that we wouldn't need to rebuild dependencies from scratch every time.
Also, it doesn't make sense to cache the registry itself, since it's also transmitted via network but this doesn't add the (un)packing overhead. (See also https://levans.fr/rust_travis_cache.html)
> Improve caching in Travis

- src/actions/hover.rs
`extract_docs` if-continue could cause endless looping if moving up & top line meta.
_after fix:_
Fixes #1168
> Fix hover infinite loop

- Cargo.lock
- Cargo.toml
Bump Racer to include https://github.com/racer-rust/racer/pull/1007.
This pulls `rustfmt-nightly` from git to reduce `rustc-ap-*` duplication (v297 -> v306).
Fixes #976.
Also this fixes our Windows CI remaining tooltip test.
r? @nrc
> Bump Racer to 2.1.16

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/actions/hover.rs
After the discussion in #1151 this change:
* Splits test_tooltip into `test_tooltip` & `test_tooltip_std`. Only the latter will be ignored to avoid running upstream.
* Remove the `--cfg=enabled_tooltip_tests` stuff, the ignored test can be run with `cargo test -- --ignored`.
* Add string diff coloured output to tooltip tests.
<details><summary>Old/resolved</summary>
<p>
I also tried to get to the bottom of the windows test failures. I managed to reproduce it on my local machine and traced the error to a **panic without a backtrace** from a rustfmt call: https://github.com/rust-lang/rls/blob/bfa1371f5cceacebe307d9ee70760296eb0ec489/src/actions/hover.rs#L785
```
error: unexpected close delimiter: `}`
--> <stdin>:5:1
|
5 | }
| ^ unexpected close delimiter
```
This was quite painful to find …
> Improve hover test_tooltip tests

- src/config.rs
3efe567b9ede ("Enhanced hover tooltips") added the `full_docs` configuration option as an `Inferrable`. However, it failed to actually merge the option during a config update, causing a panic if the client specified `full_docs` to be `null`. Example panic:
thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/config.rs:111:33
Fix this to prevent the crash.
> Properly infer full_docs

- src/actions/hover.rs
Fixes #1195.
While it should be really a 'good first issue', due to spurious macOS failures I'd say we need this sooner rather than later, especially since test_tooltip will land soon on Rust CI now (we should know better what failed and why).
@alexheretic does it look good?
> Separate tooltip tests that require Racer fallback

- src/actions/hover.rs
In principle, I'd say I prefer absolute paths for references to *outside* of the project root (or at least relative to `${CARGO,RUSTUP_HOME}` in this case) but it's what we test against now and didn't want to cause any change in behaviour now.
I'd appreciate more eyes looking at this: @ehuss @alexheretic @aloucks 
Should fix Rust CI failure https://github.com/rust-lang/rust/pull/56924 (there, we map `.cargo` to `/cargo` and the old logic only remapped paths starting from `.cargo`).
> Respect ${CARGO,RUSTUP}_HOME for tooltip relative dirs

- src/actions/hover.rs
https://github.com/rust-lang/rust/pull/52994
> Fix deprecated `trim_{left,right}` warnings

- Cargo.lock
- Cargo.toml
- src/actions/hover.rs
The `$HOME` -> `$USERPROFILE` fallback logic does not work for Windows
when running builds under `sh`. We don't canonicalize the path here so
just rely on checking `$USERPROFILE` first and that it has
`C:\Windows\Style` path instead of `/unix/one` (shape is important when
stripping prefix).
Use `home ^0.3` since that's what Cargo uses [right now](https://github.com/rust-lang/cargo/blob/1dff476dcadbf5878d640a732037d931879ed209/Cargo.toml#L38).
> Use `home_dir` from `home` crate

- src/server/mod.rs
This exchanges a compilation error for a warning-but-future-error
but at least it compiles now and I'm not exactly sure how to fix it
without cloning those `METHOD` constants on every match (which is less
than ideal, to say the least).
> Work around https://github.com/rust-lang/rust/pull/55937

- README.md
- src/actions/requests.rs
- src/build/plan.rs
- src/config.rs
I've been having a look at handling lsp in out-of-project rust files, like dependencies, for ide-rust which got me more interested in this. From the discussions in #1139 & #1106 I think we got fairly close to consensus.
* Runs racer find_definition if analysis goto has failed and `racer_completion` config is enabled. This brings the functionality in line with hover _(now in both cases racer calls are lazy)_.
* Removed `goto_def_racer_fallback` config.
* _Minor: Ignore clippy large enum lint in `BuildPlan`._
I think reusing `racer_completion` config is desirable, as the only known reason to disable this is when racer has critical performance issues with a project. In these cases we'd also not want any racer-fallbacks to run. In other cases where analysis works these fallbacks have no cost, …
> Fallback to racer definition

- README.md
- clients.md
- debugging.md
- src/main.rs
Rust 1.31 (Rust 2018) dropped the `-preview` suffix.
r? @nrc
> Change all mentions of `rls-preview` to `rls`

- src/server/mod.rs
Fixed upstream in https://github.com/rust-lang/rust/commit/21ac19d8fefb023752645fcf2517ce0fad663bf0.
> Revert NLL bug workaround

- src/build/rustc.rs
Needed for https://github.com/rust-lang/rust/pull/57392 (Rust RLS submodule already points to this commit).
> Don't pass now removed MakeGlob parameter to rustc

- README.md
As we know missing rls components in the nightly release is expected every now and then. The regular issues raised suggest either our communication isn't good enough, or the solution isn't.
I think explaining the issue in the readme a little more fully and using the error more prominently may help people find the explanation & workarounds.
> Readme: Improve missing nightly info

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/actions/notifications.rs
* Support cargo rebuilding when client does not send _workspace/didChangeWatchedFiles_ notifications.
* Update clippy `1838bfe5a9ff951ffd716e4632156113d95d14a4`
* Update cargo `907c0febe7045fa02dff2a35c5e36d3bd59ea50d`
Should fix #1240
> Support textDocument/didSave manifest cargo rebuilds

- tests/tests.rs
> tests: Add a test for rust-lang/rust#57462 and go-to-definition without racer in general.

- src/build/rustc.rs
I found some extra calls to make: https://github.com/rust-lang/rust-clippy/blob/da7aebc342b7dae444912b98dedbab22bf2a224c/src/driver.rs#L135-L136
Fixes #1241
> Add missing clippy_lint register calls

- Cargo.lock
- Cargo.toml
As in rust-lang/rust + `cargo update`
> Update clippy -> 280069dd

- README.md
- architecture.md
- contributing.md
This is the initial draft, which serves as reading material for the upcoming IDE discussion at Rust All-Hands.
Reviews, ideas about what could we include and the actual content welcome!
[Rendered](https://github.com/rust-lang/rls/blob/5ce1a02589f2a2722ca6949c4f97e6e6fce8a8ac/architecture.md)
> Add a high-level overview of the RLS

- src/build/cargo_plan.rs
- src/build/external.rs
- src/build/plan.rs
- src/build/rustc.rs
- src/lib.rs
- src/server/dispatch.rs
- src/server/io.rs
- src/server/message.rs
>  Remove crate_visibility_modifier feature

- contributing.md
> Add how RLS can be built without clippy_lints

- Cargo.lock
- Cargo.toml
We'd like to keep track with the current Rust version.
> Bump RLS to 1.34

- tests/support/paths.rs
Since the `ATOMIC_USIZE_INIT` is deprecated (figured `ONCE_INIT` is likely to follow?).
> Prefer {AtomicUsize,Once}::new

- src/actions/hover.rs
- src/actions/requests.rs
- tests/tooltip.rs
Implement optional `range` property for `textDocument/hover` response: https://microsoft.github.io/language-server-protocol/specification#textDocument_hover
> Implement range for hover response

- Cargo.lock
- Cargo.toml
- src/actions/mod.rs
- src/actions/notifications.rs
- src/lsp_data.rs
- tests/tests_old.rs
This pr tries to implement half of what's said in #1153 (reporting unused configs can be implemented in a separate pr). It introduces a new dependency on [heck](https://crates.io/crates/heck) for case conversion, add a little bit tweak to [struct Config in lsp_data.rs](https://github.com/lijinpei/rls/commit/cbeb77b03759cefe9091e4587aabb249adaff6c9#diff-5c71a9e04104a098c5f6e6f6af6a2ff5R249) so that Config'keys can be deserialized ignoring case(It basically first deserializes to a serde_json::Value, convert the case, then deserializes to the real struct Config), and add a few test-cases.
> implement kebab case config support

- Cargo.lock
- Cargo.toml
This includes `rustc-ap-*` bump to v366, which removes duplicated v306.
> Bump Rustfmt to 1.0.2

- rls-analysis/src/analysis.rs
- rls-analysis/src/lib.rs
- rls-rustc/.gitignore
- rls-rustc/Cargo.lock
- rls-rustc/src/lib.rs
- rls-vfs/src/lib.rs
- rls-vfs/src/test.rs
- rls/src/config.rs
- rls/src/lib.rs
Simple chore, removing `crate_visibility_modifier` since it didn't make the cut to Rust 2018.
@nrc IIRC someone wanted to use rls-analysis in a stable setting (although the file format continues to be very unstable) so maybe it might be a good idea to release new versions of those packages from this monorepo.
> Remove unnecessary #![feature]s

- Cargo.toml
- tests/client.rs
- tests/support/client.rs
- tests/support/client/child_process.rs
- tests/support/client/mod.rs
Started working towards more clean and abstract LSP client (hopefully server later on?) - first change separates the underlying transport used for the LSP client.
Another convenient change is implementing `Drop` for the `RlsHandle` so we don't need to call shutdown manually everywhere.
Next, I'd like to separate and not own directly `Runtime` but probably work with tokio Executors.
r? @alexheretic
> Make test `RlsHandle` transport-agnostic

- rls/src/actions/format.rs
- rls/src/actions/hover.rs
- rls/src/actions/mod.rs
- rls/src/actions/requests.rs
- rls/src/build/cargo.rs
- rls/src/build/cargo_plan.rs
- rls/src/build/external.rs
- rls/src/build/plan.rs
- rls/src/build/rustc.rs
- rls/src/lib.rs
- rls/src/project_model.rs
- rls/src/server/message.rs
- tests/support/client/mod.rs
This is mostly due to `clippy::redundant_closure` which might make sense in most
cases but in other we'd like to let type inference do the work for a
concise and readable code (e.g. `toml::de::Error::line_col` instead of
`|x| x.line_col()`).
> Apply Clippy fixes

- Cargo.lock
- Cargo.toml
- rls/src/build/cargo.rs
Cargo had a minor api change due to rust-lang/cargo#6683.
Clippy needed an update to build with latest nightly.
> Update cargo and clippy.

- Cargo.lock
- Cargo.toml
This needs crates.io releases from both https://github.com/rust-lang/rustfmt and https://github.com/racer-rust/racer
@topecongiro @kngwyu お願いします! (I hope that's correct :sweat_smile: )
> Update to rustc-ap-* v407

- Cargo.lock
- Cargo.toml
In order to match the current nightly Rust version.
> Bump RLS version to 1.35

- rls/src/main.rs
Previously this was put here to fix stack overflow on Windows: https://github.com/rust-lang/rls/pull/942
In Rust this was removed as part of the https://github.com/rust-lang/rust/pull/56732. @Zoxc could you tell why this was removed? Is that not necessary now, with the underlying architecture changes to the compiler?
> Remove now-unnecessary `link_args`

- tests/client.rs
These 4 tests seem to fail very reliably for me on macOS with an HFS filesystem (1 second resolution). This patch demonstrates one way to get them to pass. Presumably there are multiple targets being built at the same time (such as lib + lib(test)), and if they complete at the same time (exactly equal filesystem timestamps), it seems to get confused. 
I don't know enough about rls to actually fix these, but maybe this will give some hints on how to fix them. I've run the `client.rs` tests a few thousand times locally without failure. Feel free to close this PR if you'd rather not paper over the failures.
> Silence some flaky tests.

- rls-analysis/Cargo.toml
- rls-analysis/src/lib.rs
- rls-analysis/src/raw.rs
We want to transition off of rustc-serialize and onto serde, so this
commit sets up both to co-exist, gated by feature flags. Due to the fact
that they implement the same functions, only one feature flag can be
active at a time. To compile rls-analysis with serde, it is necessary to
run cargo build with the `--no-default-features` flag and the
`--features "serialize-serde"` flag.
The tests in this commit will still work with the default feature flags
but will need to be changed before the serde implementation can pass
tests.
Addresses #1354
> Add serde implementation to complement rustc-serialize

- rls/src/config.rs
This brings it in line with what's used by Rust and Rustfmt.
Closes #1414.
r? @jsgf
@bors delegate=jsgf (hopefully this works)
> Allow unstable features under "dev" channel

- rls/src/actions/format.rs
- rls/src/actions/requests.rs
- rls/src/lib.rs
- tests/client.rs
Ticks few boxes in #3. (that's an early issue!)
Closes #334.
This is currently based on https://github.com/rust-lang/rustfmt/pull/3424 and so currently blocked until it merges.
Configures Rustfmt to use `EmitMode::ModifiedLines` and parses the response - this should work with both statically-linked and externally provided Rustfmt.
@alexheretic do you think you could take a look and double-check?
> Return only modified lines in formatting responses

- rls/src/actions/format.rs
- tests/client.rs
Closes #1421.
Previously we sent `u64::max_value()` in hope that it'll be supported by editors and to signify a 'line-wide' edit but now we try to always do the right thing and send an accurate diff.
> Always send correct end column when formatting

- rls/src/lsp_data.rs
These are unused since we started using the proposed `window/progress` LSP extension. The official proposal has already been merged in https://github.com/Microsoft/vscode-languageserver-node/pull/261 so now is a good time to remove those.
> Remove obsolete custom progress reporting LSP messages

- README.md
Old one now links to the new one.
> Use new official link for the rustup components history

- Cargo.lock
- Cargo.toml
- rls/src/build/cargo.rs
- rls/src/build/cargo_plan.rs
- rls/src/project_model.rs
This updates cargo to pick up some recent API changes. Also updates clippy
to build on the latest nightly (2019-05-01).
> Update cargo, clippy

- Cargo.lock
- Cargo.toml
- rls/src/actions/format.rs
- tests/client.rs
Rather than calculating a column, use line+1, column 0 as the end of the
Range and include the final newline in the output text.
This allows for proper line removal and won't clobber existing lines when inserting new ones.
~Test still needs updating.~
Fixes #1443
> Fix TextEdit calculation.

- rls-analysis/test_data/.ignore
CC https://github.com/BurntSushi/ripgrep/issues/1284
Without this, running for example `rg ptr::NonNull` in the Rust repository floods the console with the entire contents of `src/tools/rls/rls-analysis/test_data/rust-analysis/libcore-a5db6a3445116c08.json`, which is a 3 MB single-line JSON file.
> Make ripgrep ignore test data JSON files

- contributing.md
A very small PR to the contributing.md file:
1. The link to the env_logger crate was broken: `The requested resource does not exist`
2. The example environment variable threw an error: `warning: invalid logging spec 'debug code', ignoring it` (I removed the `code`  from `RUST_LOG=rls=debug code`)
It's not much but I bumped into it and had to figure it out, it'll maybe save a few minutes to other people :)
> Fix contributing.md env_logger example

- .travis.yml
- Cargo.toml
For https://github.com/rust-lang/rust/issues/59761
As the bonus I changed Travis to test Clippy only when commit message contains words `update`, `clippy`. You can see it in the action here: https://travis-ci.com/mati865/rls/builds/114715073 https://travis-ci.com/mati865/rls/builds/114715514
That trick was borrowed from Rust: https://github.com/rust-lang/rust/blob/ca1bcfdde3f19afd68ef808cecf2ce56d08d5df4/.travis.yml#L218
> Do not build Clippy by default

- tests/support/client/mod.rs
Setting `CARGO_TARGET_DIR=somedir cargo test` would cause every test to reuse the same target dir, causing them to stomp on each other's files.  This changes it so that `CARGO_TARGET_DIR` is cleared, and each invocation of rls in the tests will use the target directory in the project where it runs.
Fixes #1466.
> Clear CARGO_TARGET_DIR for tests.

- tests/client.rs
Will need to investigate but for now I'd like to disable this altogether to ease bumping RLS submodules.
cc @topecongiro 
@ehuss any remote chance this showed up on your radar before when you investigated intermittently failing tests?
> Disable a spurious Racer test

- rls/src/cmd.rs
Since the CLI is intended for debugging purposes.
> fix(cmd): make clear_env_rust_log default to false

- rls/src/actions/format.rs
> Pass --file-lines to rustfmt only if specified

- rls/src/build/cargo.rs
Continuation of #1471, this builds on it by also filtering the `--FLAG VALUE` arguments and adding unit tests.
Closes #1471.
> Ensure that --error-format is only passed once to `rustc`

- tests/client.rs
Since switching CI to Azure Pipelines it seems that this test seems
to fail more consistently, so let's disable that for now. It helps
that we have less than a week before release - we disallow PRs that
break the tools to land in this period, so this makes landing critical
PRs smoother now.
> Disable client_find_definitions

- build.rs
- rls-analysis/Cargo.toml
- rls-analysis/benches/std_api_crate.rs
- rls-analysis/src/analysis.rs
- rls-analysis/src/lib.rs
- rls-analysis/src/listings/mod.rs
- rls-analysis/src/loader.rs
- rls-analysis/src/lowering.rs
- rls-analysis/src/raw.rs
- rls-analysis/src/symbol_query.rs
- rls-analysis/src/test/mod.rs
- rls-analysis/src/util.rs
- rls-blacklist/Cargo.toml
- rls-rustc/Cargo.toml
- rls-rustc/src/bin/rustc.rs
- rls-vfs/Cargo.toml
- rls-vfs/src/lib.rs
Converts all the remaining crates to 2018 edition and prunes remaining copyright headers (see https://github.com/rust-lang/rust/pull/57108).
> Summer cleaning

- rls-analysis/src/lib.rs
- rls-analysis/src/lowering.rs
- rls-analysis/src/raw.rs
- rls-vfs/src/lib.rs
Fixes #1491 and continues some cleanup from #1507.
> Re-export raw::Crate in rls_analysis

- rls-vfs/src/lib.rs
- rls/src/actions/hover.rs
- rls/src/actions/mod.rs
- rls/src/actions/notifications.rs
- rls/src/actions/post_build.rs
- rls/src/actions/requests.rs
- rls/src/build/cargo.rs
- rls/src/build/cargo_plan.rs
- rls/src/build/mod.rs
- rls/src/build/rustc.rs
- rls/src/cmd.rs
- rls/src/lib.rs
* Fixes remaining Clippy lints
* Prefer a named `UnitKey` type to leverage `From` impl and simplify some destructuring
* Prefer `Arc::clone` over `.clone()` (we have a very `Arc`-heavy code, it helps to spot "cheap" clones)
* Prefer `{ let a = Arc::clone(&a);... <closure> }` syntax to copy these into closure (to work around noisy `_clone` suffixed vars)
> Clean up a bit

- tests/client.rs
I believe this is the only remaining spurious tests that causes false positives in Rust CI. It'd be good to fix the underlying issue but this has prevented to land a broken toolstate fix for some time now so let's ignore it for now.
> Ignore spurious client_deglob test

- Cargo.lock
- Cargo.toml
Should fix latest nightly build failures and allow us to update RLS in the Rust tree.
> Bump rustc-ap-* crates to 542

- Cargo.lock
- Cargo.toml
This waits for the appropriate changes to be merged upstream - with this we can update RLS in the Rust tree.
cc https://github.com/rust-lang/rust/issues/63195
> Patch deps to use rustc-ap-* v546

- changelog.md
- rls/src/build/rustc.rs
Reason for that being so that non-syntax errors should still allow us to reason about which file belongs to a given crate, which specifically allows us to run a formatter even if the code contains type errors or similar.
Should make the formatter Just Work^TM in the cases where it could've technically worked before (e.g. no syntax errors).
Requires https://github.com/rust-lang/rust/pull/62679
> Collect file -> edition mapping after AST expansion

- rls/src/actions/mod.rs
- rls/src/build/plan.rs
Not being able to run rustfmt when code is building has been getting on my nerves a bit.
This pr adds a fallback to cover cases where `files_to_crates` is empty causing format requests to fail as we can't currently determine the edition to use. In these cases the manifest is read directly to determine edition.
Fixes #1148
> Fix rustfmt during builds by reading edition from manifest

- rls/src/build/rustc.rs
Enabled by https://github.com/rust-lang/rust-clippy/pull/3665.
When using Cargo build plan we always have `CARGO_MANIFEST_DIR` set so I believe this was done to support external build plan work.
r? @jsgf
> Don't forcibly set CARGO_MANIFEST_DIR as a workaround for Clippy

- rls/src/actions/notifications.rs
- rls/src/config.rs
- rls/src/lsp_data.rs
- rls/src/server/mod.rs
- tests/client.rs
Addresses https://github.com/rust-lang/rls-vscode/pull/643.
Brings back removed option from #1509 but only not to trigger the unknown option warning.
> Warn against deprecated config entries

- rls/src/config.rs
And here I thought I checked everything... :man_facepalming: 
This fixes the inferred default when passing `"rust.crate_blacklist": null` configuration option
> Fix inferred crate_blacklist default

- rls/src/build/rustc.rs
CC https://github.com/rust-lang/rust/pull/62727
> Import rustc_plugin from its new location

- rls-analysis/Cargo.toml
- rls-analysis/src/analysis.rs
- rls-analysis/src/lib.rs
- rls-analysis/src/lowering.rs
This is useful for getting all symbols in a file, for highlighting identifiers on a line or highlighted region, etc. I think it could get a little expensive, so I made it opt-in for now.
r? @Xanewok
> rls-analysis: add a feature to return all identifiers in a span.

- Cargo.lock
- Cargo.toml
- rls-ipc/.gitignore
- rls-ipc/Cargo.toml
- rls-ipc/src/client.rs
- rls-ipc/src/lib.rs
- rls-ipc/src/rpc.rs
- rls-ipc/src/server.rs
- rls-rustc/Cargo.toml
- rls-rustc/src/bin/rustc.rs
- rls-rustc/src/clippy.rs
- rls-rustc/src/ipc.rs
- rls-rustc/src/lib.rs
- rls/src/build/ipc.rs
- rls/src/build/mod.rs
- rls/src/build/plan.rs
- rls/src/build/rustc.rs
- rls/src/config.rs
- rls/src/main.rs
This is quite a lengthy patch, but the gist of it is as follows:
- `rls-ipc` crate is introduced which acts as the IPC interface along with a server/client implementation
- `rls-rustc` is enhanced with optional support for the IPC
- RLS can optionally support it via setting `RLS_OUT_OF_PROCESS` env var (like `rls-rustc` it needs to be compiled `ipc` feature)
The IPC is async JSON-RPC running on Tokio using `parity-tokio-ipc` (UDS on unices and named pipes on Windows)
- Tokio because I wanted to more or less easily come up with a PoC
- RPC because I needed a request->response model for VFS IPC function calls
- uds/pipes because it's somewhat cross-platform and we don't have to worry about `rustc` potentially polluting stdio (maybe just capturing the output in `run_compiler` would be …
> Implement support for out-of-process compilation

- Cargo.lock
- Cargo.toml
This allows us to upgrade Rust to the latest Cargo, since the
dependencies of Cargo have changed in a newer commit.
> Bump Cargo dependency to latest master

- rls-rustc/src/clippy.rs
This PR remove the incorrect `self::` import prefix on codepath guarded by `#[cfg(feature = "clippy")]`.
When clippy compiles, the `clippy` feature is enabled and trigger [this compiler error](https://github.com/rust-lang/rust/pull/64604#issuecomment-533349741).
> Fix RLS compile error for rust-lang/rust#64604 (Update clippy)

- Cargo.lock
- Cargo.toml
- rls-analysis/Cargo.toml
- rls-rustc/Cargo.toml
I had hard time upgrading `lsp-types` so it's left with old version.
> Upgrade dependencies

- Cargo.lock
Closes https://github.com/rust-lang/rls/issues/1571
> Downgrade crossbeam-utils to workaround nightly breakage

- debugging.md
It looks like there is a support for Cargo Workspaces now.
https://github.com/rust-lang/rls/issues/132
> Remove stale description for Cargo Workspaces.

- contributing.md
rustDocument/implementations is not in use.  Fix #1593
@Xanewok:
> We're not using it anymore since #936 but the documentation is outdate.
> doc: contributing: Remove outdated LSP extension

- Cargo.lock
- Cargo.toml
This PR updates rustfmt to 1.4.11, which includes a bug fix for https://github.com/rust-lang/rustfmt/issues/3945.
> Update rustfmt to 1.4.11

- rls-analysis/src/lib.rs
- rls-vfs/src/lib.rs
- rls/src/lsp_data.rs
We are getting ready to deprecate std::error::Error::description: https://github.com/rust-lang/rust/pull/66919. This PR replaces the three uses in this crate.
> Remove description() methods from Error trait impls

- rls-span/src/compiler.rs
- rls/src/actions/diagnostics.rs
Both links point to the old place of the error emitter
Closes #1604
> Correct two links to the json-error-emitter

- Cargo.lock
- Cargo.toml
- rls-rustc/Cargo.toml
- rls-rustc/src/lib.rs
- rls/src/build/rustc.rs
cc https://github.com/rust-lang/rust/pull/67821
> Rustup https://github.com/rust-lang/rust/pull/67786

- Cargo.lock
- Cargo.toml
- rls/src/actions/diagnostics.rs
- rls/src/project_model.rs
get rls in sync with latest cargo
r? @Xanewok
> deps: update cargo

- Cargo.lock
- Cargo.toml
To do so, we also upgrade the transient dependency ignore to 0.4.11.
@mati865 I'm sorry for not addressing #1614 earlier. I understand to fix the underlying issue, we really need to bump the `crossbeam-utils` dep to 0.7?
To do so we need to coordinate another realease with Rustfmt (and so also bump the `rustc-ap-data-structures`), I believe.
> Update crossbeam-channel to 0.4

- Cargo.lock
- Cargo.toml
- azure-pipelines.yml
- rls-rustc/Cargo.toml
- rls-rustc/src/ipc.rs
This should prevent memory leaks which probably happen in cargo/rustc, which are not intended to be running as a long-running process.
Refs: #1188
> By default use out-of-process compilation

- rls-rustc/src/lib.rs
- rls/src/build/rustc.rs
Upstream `save_analysis` crate has been updated to work on HIR tree
directly instead of AST and thus does not require access to the
expanded AST anymore.
> Do not pass `expanded_crate` as argument to `process_crate` anymore

- Cargo.lock
- Cargo.toml
- ci/azure-install-rust.yml
- tests/fixtures/hover/save_data/test_tooltip_mod_use_external.rs.0004_012.json
- tests/fixtures/hover/save_data/test_tooltip_mod_use_external.rs.0005_012.json
- tests/fixtures/hover/save_data/test_tooltip_std.rs.0009_012.json
- tests/fixtures/hover/save_data/test_tooltip_std.rs.0015_017.json
- tests/fixtures/hover/save_data/test_tooltip_std.rs.0015_025.json
Related to addressing the current broken toolstates on nightly
https://github.com/rust-lang/rust/issues/76145
https://github.com/rust-lang/rust/issues/76146
> bump racer and rustfmt versions

- rls-rustc/src/lib.rs
- rls/src/build/rustc.rs
- tests/fixtures/hover/save_data/test_tooltip_mod_use_external.rs.0004_012.json
- tests/fixtures/hover/save_data/test_tooltip_mod_use_external.rs.0005_012.json
r? @Xanewok -- I think this should fix rust-lang/rust master
> Adjust for upstream changes

- tests/client.rs
In `tests/client.rs`, `client_dependency_typo_and_fix` was failing in my
Fedora builds of the rust toolchain. That uses `--enable-vendor`, and
the source package only has `version_check 0.9`, but this test is trying
to correct to `version_check 0.1`.
Nothing against `version_check`, but I ported this test to use `autocfg`
instead. It's also fast to compile and available in the vendored source
package, and it has a stable version 1 so this problem won't recur.
> Test typos with autocfg

- Cargo.lock
- Cargo.toml
- rls-ipc/src/rpc.rs
- rls-rustc/src/lib.rs
- rls/src/actions/requests.rs
- rls/src/build/ipc.rs
- rls/src/build/plan.rs
- rls/src/build/rustc.rs
See https://github.com/rust-lang/rust/issues/80576. This un-breaks the build of RLS after https://github.com/rust-lang/rust/pull/79576 broke it.
> Add edition 2021.

- Cargo.lock
- Cargo.toml
- rls-ipc/Cargo.toml
- rls-rustc/Cargo.toml
- rls-rustc/src/ipc.rs
- rls-rustc/src/lib.rs
- rls/src/build/ipc.rs
- tests/client.rs
- tests/support/client/child_process.rs
- tests/support/client/mod.rs
Helps with #1695 and #1693 (still needs a bump to Tokio 1.0)
> Use Tokio 0.2

- Cargo.lock
- Cargo.toml
- rls-analysis/Cargo.toml
- rls-analysis/src/analysis.rs
- rls-analysis/src/lowering.rs
- rls-analysis/src/symbol_query.rs
Bumps itertools, fst, and rayon's dependencies, which allows for two
dependencies to be removed from the lockfile.
Slightly alters fst::Map's signature because it is now generic.
> itertools = 0.9, fst = 0.4

- tests/support/mod.rs
In case we don't want to introduce another env var to rustc CI script
cc https://github.com/rust-lang/rust/pull/84412
r? @ehuss
> Bump default integration test message timeout to 30s

- .gitattributes
When doing a `git grep` (of rls or of rust-lang/rust with
`--recurse-submodules`), if the grep happens to match within the huge
rls-analysis test data files, the resulting multi-megabyte single-line
can cause a text pager to grind to a halt and have trouble scrolling
(especially scrolling backwards).
These test data files are autogenerated and aren't formatted for human
consumption, so mark them as binary, which causes `git grep` to instead
just state that they match without printing the matching "line".
> Mark huge rls-analysis test data files as binary to filter greps

- Cargo.lock
- Cargo.toml
Targeting the bump-rustc-ap version as that's what appears to be the target for the submod bump PR in r-l/rust
> bump rustfmt with test resolution

- README.md
It wasn't obvious to me where to place options for
"didChangeConfiguration", so this could help others.
VSCode adds the prefix automatically when editing settings.json but
I didn't use that.
> Document that configuration options live in a "rust" object

- Cargo.lock
- Cargo.toml
- rls-rustc/src/lib.rs
- rls/src/build/rustc.rs
rust-lang/rust#83813 made some changes to SourceMap and RealFileName. Now to get a string from a `rustc_span::FileName` or `RealFileName` (`working_dir` in `rustc_span::Session` is now a `RealFileName` because it may be remapped), we need to specify if we would like the local filesystem path or remapped path via `--remap-path-prefix`.
There are two files affected, the context very similar in both. I'm not entirely sure if we want the local path or remapped path here, so I just picked local path as a placeholder for opening this PR. 
Closes - after updating rls module in rustc repo - https://github.com/rust-lang/rust/issues/85225
> Sync with rustc_span changes

- rls-span/src/lib.rs
Closes rust-lang/rust#85824
This replaces the `unsafe impl Step` with `impl Step` and `unsafe impl TrustedStep`. This is the only location of the `Step` trait in this repository.
> Update `Step` trait implementation

- rls-ipc/src/rpc.rs
- rls/src/lsp_data.rs
> Fix typos “a”→“an”

- rls/src/actions/diagnostics.rs
This is to match rustc's behavior, and to avoid weird diagnostic boxes
that look like this:
unnecessary trailing semicolons
note: `#[warn(redundant_semicolons)]` on by default
help: remove these semicolons: ``
After this change, the last line should look like this:
help: remove these semicolons
> Only show suggested code when it is non-empty

- Cargo.lock
- Cargo.toml
- rls-ipc/Cargo.toml
- rls-rustc/Cargo.toml
- rls-rustc/src/lib.rs
- tests/client.rs
- tests/support/client/child_process.rs
- tests/support/client/mod.rs
Closes #1695
Closes #1693
Just enabled by https://github.com/tokio-rs/tokio/pull/3388.
Work in progress to prune winapi 0.2, still needs patches upstreamed that migrate `parity-tokio-ipc` and `jsonrpc-*` crates to Tokio 1.0. Let's see what CI has to say, first.
Blocked on:
> Bump to Tokio 1.0

- Cargo.lock
- Cargo.toml
- rls-rustc/Cargo.toml
- rls-rustc/src/clippy.rs
- rls-rustc/src/lib.rs
- rls/src/actions/mod.rs
- rls/src/build/external.rs
- rls/src/build/rustc.rs
- rust-toolchain
This will unblock the Clippy sync to rustc rust-lang/rust#91154
Changes:
- Bump nightly version
- Bump Clippy version
- Bump rustfmt version
- Fix fallout
- Run `cargo update`
I tested this locally with `cargo test --all-features`
> Bump nightly, clippy and rustfmt versions

- rls-analysis/src/lib.rs
Previously, `raw::deserialize_crate_data` and `raw::read_crate_data` functions were make public inside the raw module, but I did not see that the `raw` module itself was not public. I now realize that the functions should also have been exposed in the main library file as public functions on the primary module. This PR addresses that
> Expose public functions from private raw module

- README.md
I added this in 008027d and probably used server because my LSP client
happens to be a server as well. What we actually mean is the editor,
more specifically the LSP client. Sorry for the noise!
> README: clarify that configuration is sent by an LSP *client*

- Cargo.lock
- Cargo.toml
- rust-toolchain
- Need this PR from racer to remove old rustc-ap packages:  https://github.com/racer-rust/racer/pull/1174
Also @flip1995 may have a more proper PR in-progress. Once racer pushes a new release then the pinned git hash dependency can be avoided.
#1758
https://github.com/rust-lang/rust/issues/91543
> Update rustc channel, rustfmt, and racer to fix the build

- tests/client.rs
This error message recently failed, and prevented RLS from building on beta. Beta has been taken care of, and this PR backports that commit over to the master branch.
> Fix expected diagnostic for crate name typo

- architecture.md
Signed-off-by: JmPotato <ghzpotato@gmail.com>
> Update the architecture.md file with the latest repo and code links

- Cargo.lock
- Cargo.toml
- rls/src/project_model.rs
In rust-lang/cargo@7248f4b70da464b9ed7839e0f26110b6664b6ee6,
`cargo::core::resolver::resolve::Resolve::extern_crate_name` was renamed
to `extern_crate_name_and_dep_name` and started to return both extern
crate and dep name. RLS only needs extern crate name at this moment.
Not sure if there is any crate using rls as a libbrary directly. 
I assume no, so I change the type of the pub field `Dep.crate_name`.
If this is not appropriate, I can alternatively keep it as `String`.
> Bump cargo version

- Cargo.lock
This PR pulls https://github.com/racer-rust/racer/pull/1177 into RLS, fixing the build on the parallel compiler.
> Rump racer to fix parallel compiler failure

- rls-span/src/compiler.rs
Follow up https://github.com/rust-lang/rust/pull/74862.
https://github.com/rust-lang/rust/blob/master/src/librustc_errors/json.rs returns page not found.
This PR fixes the incorrect URL.
> Fix an incorrect URL

- rls/src/actions/run.rs
- tests/client.rs
- tests/fixtures/lens_run/src/main.rs
Make test regex a little bit more permissive.
This will allow external libs that have special test macro to be recognize as valid test case.
For example, following macros will be recognized as valid test case:
```
#[test]
#[tokio::test]
#[async_std::test]
#[actix_web::test]
#[actix_rt::test]
#[actix_web::rt::test]
```
Issue was at beginning reported in `vscode-rust` repo [here](https://github.com/rust-lang/vscode-rust/issues/756) and author switch from `rls` to `rust-analyser`.
Looking at `rust-analyser`, everything that has `test` in function attributes is recognized as a test (see code [here](https://github.com/rust-analyzer/rust-analyzer/blob/2ac1ffc0f3bef98f74b0c3d7ac2371d73c75ce5c/crates/ide_assists/src/utils.rs#L71)).
Running test or not is a choice left to user, even if it does not …
> Update regex use to match test for external librairies
