rust-lang/rls

src/actions_ls.rs
src/ls_server.rs

I apologize for breaking the build, it is fixed here, I have added new enum support for the TextEdit.

Adding new ResponseData support for TextEdit

---

src/server.rs

Issue #23 was closed ~16 days ago.

Remove resolved FIXME comment

---

src/ls_server.rs

A stab at #45.
~~This uses a recursive macro to build up both things simultaneously.
That does mean that with more messages, we can hit the macro expansion limit, but I don't see how to do the filtering without recursion.~~
This doesn't do anything for LsService::handle_message (yet) but it should be doable.
I manually checked that the `--pretty expanded` output is equivalent.

[rfc] Generate the Method enum and parse_message function.

---

src/build.rs

Fixes #81
---
I'm able to get httparse working on Windows, though the initial compile prints the below to stderr. Not sure if it's a problem. Gotodef and hover do work without using Racer.
```
ERROR:rustc_save_analysis::dump_visitor: Mis-calculated spans for path 'Error::HeaderName'. Found 1 spans, expected 2. Found spans:
ERROR:rustc_save_analysis::dump_visitor:     'HeaderName' in src\lib.rs, line 104
ERROR:rustc_save_analysis::dump_visitor: Mis-calculated spans for path 'Error::HeaderValue'. Found 1 spans, expected 2. Found spans:
ERROR:rustc_save_analysis::dump_visitor:     'HeaderValue' in src\lib.rs, line 106
ERROR:rustc_save_analysis::dump_visitor: Mis-calculated spans for path 'Error::NewLine'. Found 1 spans, expected 2. Found spans:
ERROR:rustc_save_analysis::dump_visitor: …
```

Account for arguments with double quotes when building rustc commandline.

---

src/actions.rs
src/server.rs

Given my understanding of the RLS structure, this commit addresses the two points mentioned in #94. It marks the file as saved in VFS and triggers a rebuild.

Handle DidSave notification by triggering rebuild

---

src/actions.rs

This includes secondary messages taken from spans into the message.
For example
```
fn main() {let x: u64 = 0u32;}
```
will render as
```
mismatched types
expected u64, found u32
```
instead of only showing `mismatched types`.

Provide more helpful compiler messages

---

src/actions.rs

Since git can't properly show what exactly I did I am writing that here:
The code from 89 to 95 was extracted into `clear_build_results`.
The code from 96 to 128 was extracted into `parse_compiler_messages`.
Before the code locked the mutex for each addition. I did that it lock before.
It there was some motivation please let me know and I will revert it.
The code from 130 to 145 was extracted into `convert_build_results_to_notifications`.
@jonathandturner,
Why do you use `.iter()` in `for`?

Extracted some pieces of code into functions

---

src/lsp_data.rs
src/server.rs
src/test/mod.rs

First step moving over to lsp 3.0

---

README.md
src/build.rs
src/config.rs

Add sysroot configuration to rls.toml

---

README.md

+Mention pkg-config as build dependency

---

src/server.rs

This fixes #45.
For every `Method`/`Notification` enum we can either specify an arbitrary expression to evaluate when handling a message or use a default handler following existing convention:
`this.handler.<action_name>([id,] params, &*this.output)`.
Few things to note:
* I'd love to get rid of `trace_params` as I think there may be better idea to handle an optional enum payload token in `trace!` call
* Possibly lines with `trace!` call are too long, but I figured it doesn't add to the logic itself, so throwing a one-liner just to inform of a trace is acceptable
* I defined macros inside impl for LsService, as the macro is closely related only to that particular scope and it seemed somewhat self-contained, but if needed I can move it to top-level so it generates whole …

LsService::handle_message match replaced with macro

---

README.md

I was verifying https://github.com/rust-lang-nursery/rls/issues/274 and noticed a few leftovers when you updated the docs.
[Rendered](https://github.com/kosta/rls)
Thank you so much for your amazing work. `rls` so incredibly great!
Cheers,
Kosta

Change readme "Switch to nightly" to "Update nightly"; Fix typo

---

src/actions/change_queue.rs
src/actions/mod.rs
src/main.rs

Sequentialise all changes to the VFS

---

src/actions/mod.rs

@nrc is this what we wanted here, where Debug impl wasn't yet available for ThreadId?

Use stable Debug impl for ThreadId

---

contributing.md

Adds note about installing cmake on Windows.

---

src/actions/mod.rs
src/build.rs
src/main.rs

Another attempt, this one uses many less threads. Hopefully it is simpler and more robust.
r? @Xanewok

Rewrite the build queue

---

src/build/cargo.rs
src/build/mod.rs
src/build/rustc.rs
src/config.rs

As far as I understand issue #368, this pr should fix it.

Unsets RUST_LOG before calling cargo/rustc

---

README.md

Update README.md with new options from https://github.com/rust-lang-nursery/rls/pull/409.

Mention new `workspace_mode` option in README.md

---

src/main.rs

Found myself wondering if there were any other arguments other than "--version" so created a "-- help"
Would appreciate some suggestions on wording.

Adds "--help" to command line args

---

Cargo.lock
src/build/cargo.rs

I need it to be updated for https://github.com/rust-lang/rust/pull/43009

Update to last cargo version

---

README.md

Updated documentation regarding the rls toml file as per discussion in https://github.com/rust-lang-nursery/rls-vscode/issues/107

remove reference to rls toml

---

src/actions/mod.rs

Personally I am using the vim keymap for VSCode and found the requirement to select the * too frustrating. Instead of failing with an empty selection error, let RLS figure out where the * character is.
RLS will behave identical if a selection is provided and will perform a best effort if the selection is empty, meaning it searches in the line for all * and if there is exactly one pretend it was selected.

Deglob: Allow to deglob a line without selecting the * character

---

src/build/cargo.rs

`init()` is called each time `rustc` command is prepared, so we ended up calling it as many times as there were `rustc` invocations for the package/workspace.
To initialize the packages we only need `Workspace`, which we do create already when creating `RlsExecutor` - so just pass it and use it when calling `RlsExecutor::new()`.
@nrc as you said when I first introduced the workspace_mode, this should probably be in a separate enum to better split `cur_package_id` and `member_packages` logic/storage, but I think it'd be good to do once the workspace_mode design stabilises a bit. 
Related: https://github.com/rust-lang/cargo/pull/4416

Initialize RlsExecutor during `new()` instead of during `init()`

---

src/main.rs

It's my first rust stabilization PR and it's with submodules to boot so might have done something completely wrong. Sorry for that!

stabilizing feature iterator_for_each for rust 1.22.0

---

src/server/mod.rs

This should solve the problems introduced by https://github.com/rust-lang-nursery/rls/pull/488 . I tested this both on Sublime and VS Code.

Made NoParams deserializable from any type.

---

src/build/cargo.rs

Fixes #483.
When we panic inside a different thread, while holding all the necessary
locks, we effectively poison them. This in turn, makes any subsequent
compilation runs impossible and blocks the RLS.
Instead of panicking, the Result control flow is introduced when running
Cargo build and on any encountered error we just return early and
report the error, but also releasing any acquired lock during the routine.
-----
I only have anecdotal evidence, but just as a side note, despite the
change not being too big, with it, the RLS feels a lot more stable and it
didn't get into corrupt state for me yet.

Use Result instead of panicking in case of a failed Cargo build routine

---

README.md

Ditto of https://github.com/rust-lang-nursery/rust-bindgen/commit/badafb6a967cc8f0533af8926405eac395d4b4fa, seems like a good thing to have to attract new contributors.
r? @nrc
(Should I open one for `rls-vscode`?)

Mention impl period in README.md

---

src/actions/mod.rs

Fixes #486.
Invalid spans (e.g. column range (12, 11)) can no longer be returned. Also properly points to a word behind a cursor if there is any.
Separated word-finding logic into a pure function (`find_word_at_pos`) and added a related unit test for it.
r? @nrc

Fix a bug in `convert_pos_to_span`

---

src/build/cargo.rs

In `workspace_mode` it's possible to run the compilation and fetch the resulting multiple `Analysis` and so it seems appropriate to generate with `pub_only: true` only for externally compiled crates. This should work in a single package mode, as well.
@nrc r?
(This fixes an intermittent bug that where `pub_only: true` analysis often replaced the 'full' one for a given crate in the `workspace_mode`)

Emit only public symbols only for external deps during Cargo routine

---

src/server/mod.rs

Previously the `msg_string` was used to compare to `ExitNotification::METHOD`, but `msg_string` was the `String` containing raw message, so the condition was never met.
Now it also attempts to parse the message to get more structured method and it compares that.
As a side note, it'd probably be a good idea to make `LsService::run` return a value (like an resulting exit code), because currently it's impossibly to write a test that asserts that a server indeed quits (the `::std::process::exit` aborts the test runner) and to catch when it quits to dump diagnostic data by the profiler (otherwise it'd have to handle a custom message or a signal).

Fix shutdown -> exit logic

---

Cargo.lock
Cargo.toml
src/actions/post_build.rs

This should finalize workspace support in the RLS, modulo additional features such as tests/benches/examples :tada:
cc #132

Use rls-analysis 0.8

---

src/actions/mod.rs
src/actions/notifications.rs
src/actions/requests.rs
src/build/cargo.rs
src/build/mod.rs
src/cmd.rs
src/config.rs
src/lsp_data.rs
src/main.rs
src/server/io.rs
src/server/mod.rs

See each commit's message for details.
r? @nrc

Deny missing docs

---

src/cmd.rs

For #292.
Added sensible default parameters.

Add `format` command to CLI

---

src/test/harness.rs

* No test required the filtering of outgoing messages. So it can just be removed.
* Generate sequential IDs starting from 0x0100_0000. It is an arbitrary distinctive value.
* Change while loop in `expected_messages` to < instead of != as this otherwise will cause timeouts instead of an error, when more messages than expected arrive.

Improve test harness: Record server to client messages

---

Cargo.lock
Cargo.toml
src/actions/requests.rs

+ update languageserver-types to version 0.14

Include snippets with textDocument/completion

---

Cargo.lock
Cargo.toml
src/actions/requests.rs
src/lsp_data.rs

It implements the overlap method in an extension trait, as it is a foreign type.
The languageserver-types update is required to make Position implement Ord.

Return CodeAction for any overlapping range, not just identical ranges (#599)

---

src/build/cargo.rs
src/config.rs

This resolves #338. I also have a branch ready for the respective configuration in vscode-rls. I cannot think of a way to test this though. What would you recommend here?

Add configuration for number of Cargo jobs

---

clients.md

Add workspace/symbol to required message support section

Add workspace/symbol to clients msg support

---

Cargo.lock

Fixes the build against the most recent nightly.
r? @nrc

Upgrade rustfmt-nightly

---

src/cmd.rs

@nrc It seems that `CodeAction` doesn't use the `CodeActionContext` of the `CodeActionParams`, and if i understand correctly, `start_col`,`end_col` and `end_row` is not useful in `make_deglob_actions`. I am confused, is it necessary to also pass in these arguments? Did I mistake something?
When I `cargo run --cli`, and `code_action test_data/deglob/src/main.rs  12 12 12 13` get back `[]`. I am sure 12 is the right line index. I have tested it with a warn!. And [reference of main.rs line 13](https://github.com/rust-lang-nursery/rls/blob/master/test_data/deglob/src/main.rs#L13).

Add CodeAction to the command line interface, for #292.

---

src/cmd.rs

Add ResolveCompletion to command-line interface, for #292.
I don't know how to test `ResolveCompletion`, or do I need to test it? The `handle` function of `ResolveCompletion` does nothing but return the same `CompletionItem`.
Maybe I should just provide an empty bin project and pass in some arbitrary strings?
Could anyone give me some pointers?

Add ResolveCompletion to command-line interface, for #292.

---

Cargo.lock
Cargo.toml

Bumps rustfmt-nightly to 0.3.5.

Fix nightly compilation

---

Cargo.lock
Cargo.toml
src/main.rs
src/test/harness.rs
src/test/mod.rs

New env_logger adds UTC time & colour to logs

Upgrade log 0.3 -> 0.4

---

tests/support/mod.rs
tests/tests.rs

Properly handle void params in integration test harness

---

src/server/mod.rs

Fixes #665. (that's the last part)

Use error log severity for errors stopping server

---

Cargo.lock
Cargo.toml

Bump rls-rustc to 0.2

---

README.md

Update documentation on defaults and `unstable_features`

---

Cargo.lock
Cargo.toml
src/build/cargo.rs
src/build/mod.rs
src/build/plan.rs
src/lsp_data.rs
src/main.rs

 Autodetect the package currently being edited 

---

src/actions/work_pool.rs

Minor update for the notes in work_pool to reflect the final merged logic.

Update work_pool comments

---

README.md

We don't say "RLS: done" anymore.

Update the status indicator example

---

README.md

Mention new configuration options in README.md

---

.travis.yml
Cargo.toml
src/actions/mod.rs
src/actions/requests.rs
src/config.rs
src/main.rs
src/test/mod.rs

r? @nrc 
the discussion in https://github.com/rust-lang/rust/pull/49135 sounds to me like rustfmt being a conditional feature is not necessary

Unconditionally use rustfmt in rls

---

src/actions/requests.rs

This matches what we already do for the workspace symbols endpoint.

Add container_name information to symbols response

---

src/config.rs

@peddermaster2 thanks for spotting this raw string typo.

Improve clippy_preference serde expecting message

---

src/build/cargo.rs

This sets the JSON flags at inside the Cargo hook rather than RUSTFLAGS to avoid trashing fingerprints.
Also, the RUSTFLAGS logic have been refactored to allocate much less.

Inject error-format at late stage

---

Cargo.lock
Cargo.toml

Fixes latest nightly compile with clippy feature

Update clippy -> 0.0.193

---

Cargo.lock
Cargo.toml

Fix nightly-2018-04-18 compile.
* clippy -> `0.0.195`
* rustfmt -> `dd807e2`

Update clippy, rustfmt

---

Cargo.lock
Cargo.toml

* Update clippy to compile with latest nightly
* Update cargo inline with latest nightly
* cargo update

Update clippy & cargo

---

Cargo.lock
Cargo.toml

Fix latest nightly compile (clippy)

Update clippy -> 0.0.197

---

Cargo.lock
Cargo.toml

Also update languageserver-types `0.41`.

Update clippy 0.0.199

---

Cargo.lock
Cargo.toml
src/actions/post_build.rs
src/main.rs

Also update rustfmt -> f3906267
Fixes #743

Prevent duplicate diagnostics

---

src/lsp_data.rs

Add docs to completion

---

src/server/io.rs

Instead of returning Option, return Result with information why reading failed. 
It is mostly used in unit tests to make debugging easier, but we could also consider changing MessageReader to expose that to server.
In addition to using Result, this commit also validates the 'Content-Type' header.

Return Result from server::io::read_message.

---

Cargo.lock
Cargo.toml
src/actions/requests.rs
src/lsp_data.rs

I have to also update rls-vfs after https://github.com/nrc/rls-vfs/pull/20 is merged

Update clippy and racer

---

src/actions/mod.rs

This was observed in VSCode (they're using naively parsed file URIs - https://github.com/Microsoft/vscode-languageserver-node/issues/105) but it's not limited to that, since drive letters in file URIs are case-insensitive, bare `file:` scheme can be used etc.
More info in the comment: https://github.com/rust-lang-nursery/rls/pull/983/files#diff-53ac0aa2d451315631bac6f85bcfb7bdR469
@nrc RLS performing a rebuild when adding deps in Cargo.toml seems important for the 1.0 experience on Windows - should we aim to include this in the 1.0 release?

Fix rebuilds on Cargo.{toml, lock} file changes (Windows-only)

---

Cargo.lock
Cargo.toml
src/actions/hover.rs
src/actions/mod.rs
src/actions/notifications.rs
src/actions/requests.rs
src/main.rs
src/project_model.rs

https://github.com/rust-lang-nursery/rls/pull/965, but with more explicit project model and caching.

Extended project model

---

src/project_model.rs

This should handle things like package renames.

Use modern API to get dep's extern crate name

---

Cargo.lock
Cargo.toml
src/lsp_data.rs

This part 2/3 for fixing rust-lang/rust#53440.

Bump rls-data and rls-analysis versions.

---

src/build/rustc.rs

see https://github.com/rust-lang/rust/pull/52953

codemap -> source_map

---

src/lsp_data.rs
src/test/mod.rs

Update SymbolKind conversion to LSP 3

---

Cargo.lock
Cargo.toml
build.rs
src/main.rs

See https://github.com/rust-lang-nursery/rust-clippy/pull/3137#issuecomment-419348203

fix build and use clippys rustc_tools_util to generate version information

---

Cargo.lock
Cargo.toml

Bump Clippy to Rust CI version

---

Cargo.toml
src/actions/requests.rs
tests/tests.rs

Fix use statement function suggestions

---

Cargo.lock
Cargo.toml
src/actions/hover.rs
src/build/external.rs
src/test/lens.rs
src/test/mod.rs
tests/support/mod.rs
tests/tests.rs

test/support/mod.rs
src/test/lens.rs
src/actions/hover.rs
fix redundant_clone warnings (don't clone)
test/tests.rs
src/build/external.rs
fix into_iter_on_ref (into_iter() -> iter())

fix a couple of clippy warnings

---

README.md
clients.md
contributing.md
debugging.md
src/build/rustc.rs
src/test/mod.rs

Update nursery links -> rust-lang

---

test_data/hover/save_data/test_tooltip_std.rs.0025_017.json

Due to https://github.com/rust-lang/rust/pull/53586.

Update String tooltip test

---

src/build/cargo.rs

Use .cargo/config build.target-dir + "/rls"

---

README.md

Clarify show_hover_context default value

---

Cargo.lock
Cargo.toml

As currently referenced upstream.

clippy -> a3c77f6a

---

Cargo.lock
Cargo.toml

https://github.com/rust-lang/rust/pull/57213

Update Clippy... again

---

tests/client.rs

Closes #1232.
Will run this on Travis a couple of times to see if this doesn't backfire :boom:

tests: Only request Racer completion once

---

Cargo.lock
Cargo.toml

https://github.com/racer-rust/racer/compare/v2.1.16...v2.1.17

Bump racer to 2.1.17

---

debugging.md

Add other missing RLS component case

---

Cargo.lock
Cargo.toml

Fixes latest nightly compilation.
* clippy -> `5725726`
* cargo update

Update clippy & lock

---

Cargo.lock
Cargo.toml

related with https://github.com/racer-rust/racer/pull/1016 and https://github.com/rust-lang/rust/pull/58356

Update racer from 2.1.17 to 2.1.18

---

rls-analysis/benches/std_api_crate.rs
rls-analysis/examples/print-crate-id.rs
rls-analysis/src/analysis.rs
rls-analysis/src/lib.rs
rls-analysis/src/listings/mod.rs
rls-analysis/src/loader.rs
rls-analysis/src/lowering.rs
rls-analysis/src/raw.rs
rls-analysis/src/symbol_query.rs
rls-analysis/src/test/mod.rs
rls-data/src/lib.rs
rls-rustc/src/lib.rs
rls-span/src/compiler.rs
rls-span/src/lib.rs
rls-vfs/benches/bench.rs
rls-vfs/src/lib.rs
rls-vfs/src/test.rs

https://github.com/rust-lang/rls/pull/1304 but for pulled subcrates.
r? @alexheretic

Format all pulled subcrates

---

Cargo.lock
Cargo.toml
rls/src/actions/post_build.rs
rls/src/build/rustc.rs

Bump clippy

---

Cargo.lock
Cargo.toml

Bumped clippy_lints version to rev c81e43b92c83bca75337ac26a296b909a6a98ab1

---

Cargo.lock
Cargo.toml
tests/client.rs
tests/fixtures/reformat_with_range/src/main.rs

In case it's needed by https://github.com/rust-lang/rust/pull/59454.

Update Rustfmt to 1.2

---

Cargo.lock
Cargo.toml

To account for the newest nightly version

Bump version to 1.36

---

README.md

Clarify how clippy_preference works in README

---

tests/fixtures/borrow_error/Cargo.toml
tests/fixtures/borrow_error/src/main.rs

Rebrake borrow error test

---

contributing.md

Just a cheap attempt at landing commit 2000.

doc: contributing: minor editing to the CLI section

---

rls/src/actions/run.rs

Fixes multiple issues linked to the previous regex being too narrow:
* [Comments preventing lenses from showing](https://github.com/rust-lang/rls/issues/1068)
* [Other macros disabling the lenses](https://github.com/rust-lang/rls-vscode/issues/432)
* Probably some others

Changed test detection regex to expand its scope

---

rls-span/src/lib.rs

This lets users iterate over ranges of rows or columns.
r? @Xanewok

Span: Implement Step for Row and Column

---

Cargo.lock
Cargo.toml

cc @topecongiro
- https://github.com/rust-lang/rust/issues/64180
- https://github.com/rust-lang/rust/issues/64179

Update Rustfmt and Racer to pull in rustc-ap-* v581

---

Cargo.lock
Cargo.toml

cc https://github.com/rust-lang/rust/pull/64279

Update Rustfmt and Racer to pull in rustc-ap-* v583

---

rls-rustc/src/clippy.rs
rls-rustc/src/lib.rs
rls/src/build/rustc.rs
tests/client.rs

~Also sets up CI to run checks against newest Rust master branch.~
Tested locally using `rustup-toolchain-install-master` and seems to work!
Will work on checking PRs against Rust master branch in a separate PR.

Unbreak latest nightly

---

Cargo.lock
Cargo.toml

cc https://github.com/rust-lang/rust/issues/65084

Update racer and rustfmt to pull in rustc-ap-* v606.0.0

---

tests/client.rs

Slight diagnostic change due to https://github.com/rust-lang/rust/pull/66389.

Fix test for latest nightly.

---

rls-ipc/src/rpc.rs
rls-rustc/src/ipc.rs
rls/src/build/ipc.rs
rls/src/build/rustc.rs

Already pulled in the Rust tree.

Fix nightly by implementing missing FileLoader::abs_path

---

Cargo.lock
Cargo.toml
rls/src/build/cargo.rs

cc https://github.com/rust-lang/rust/issues/71753

update to latest cargo

---

Cargo.lock
Cargo.toml

fixes rls build with latest master toolchain

deps: update racer and cargo

---

Cargo.toml

Companion to https://github.com/rust-lang/rust/pull/77819

Update crossbeam-channel to avoid UB

---

Cargo.lock
Cargo.toml

Refs https://github.com/rust-lang/rust/issues/78340 and https://github.com/rust-lang/rust/issues/78341

bump rustfmt to v1.4.24

---

Cargo.lock
Cargo.toml

Refs https://github.com/rust-lang/rust/issues/81582 and https://github.com/rust-lang/rust/issues/81583
r? @Xanewok

deps: bump racer and rustfmt

---

Cargo.lock
Cargo.toml

refs https://github.com/rust-lang/rust/issues/83459
refs https://github.com/rust-lang/rust/issues/83460
r? @Xanewok

bump racer and rustfmt

---

rls-analysis/src/raw.rs

Kythe's Rust indexer [currently makes use](https://github.com/kythe/kythe/blob/master/kythe/rust/indexer/src/indexer/save_analysis.rs) of the `read_analysis_from_files` function, but for our use case we'd prefer to have the ability to load an analysis from a specific path and, more importantly, the ability to deserialize an analysis directly from string contents.

Expose more functions for processing analysis files

---

rls/src/config.rs
rls/src/server/mod.rs

See https://rust-lang.zulipchat.com/#narrow/stream/301329-t-devtools/topic/rls.20deprecation
cc https://github.com/rust-lang/vscode-rust/pull/956

Add deprecation notification
